export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const html = `<!doctype html>
<html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BENJADMIN · Supabase monitoring</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#07111d;color:#e8f5f4;font:14px Inter,system-ui,sans-serif}.shell{max-width:1040px;margin:0 auto;padding:32px}.eyebrow{font-size:12px;letter-spacing:.12em;color:#38d6c7;font-weight:800}h1{font-size:30px;margin:7px 0 8px}p{color:#a8bdc4;line-height:1.55}.callout{border:1px solid #735f24;background:#1d1a0f;color:#f2dda0;border-radius:10px;padding:12px 14px;margin:12px 0}.tokencheck{font-size:12px;font-weight:800;margin-top:8px}.tokencheck.ok{color:#68e6b6}.tokencheck.bad{color:#ff98a8}.authhelp{display:none;border:1px solid #854050;background:#24131a;border-radius:9px;padding:12px;margin-top:12px}.authhelp.is-visible{display:block}.status{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:#27404b;border:1px solid #27404b;border-radius:14px;overflow:hidden;margin:22px 0}.status>div{background:#0d1a29;padding:15px}.status span{display:block;color:#7e9da7;font-size:11px;margin-bottom:6px}.status strong{font-size:14px}.card{background:#0d1a29;border:1px solid #27404b;border-radius:14px;padding:21px;margin:0 0 18px}.card h2{font-size:17px;margin:0 0 8px}.field span{display:block;font-size:12px;font-weight:700;color:#9bb4bc;margin:15px 0 7px}.field input{width:100%;border:1px solid #31545e;background:#07111d;color:#eefafa;border-radius:9px;padding:12px 14px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:13px}button,a.button{border:1px solid #2f9d90;background:#153d3a;color:#dffbf7;border-radius:8px;padding:9px 13px;font-weight:800;text-decoration:none;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.secondary{background:#152432;border-color:#385366}.danger{background:#351c25;border-color:#854050;color:#ffbbc7}.ok{color:#68e6b6}.warn{color:#ffd47a}.error{color:#ff98a8}.message{color:#69e5b4}.small{font-size:12px}.toplinks{display:flex;justify-content:space-between;gap:12px;align-items:center}@media(max-width:760px){.shell{padding:20px}.status{grid-template-columns:1fr 1fr}}
</style></head><body><main class="shell">
<div class="toplinks"><div><div class="eyebrow">BENJADMIN DEVELOPER GRID · SYSTEM HEALTH</div><h1>Supabase monitoring bekötése</h1></div><a class="button secondary" href="/admin" rel="noreferrer">BENJADMIN admin</a></div>
<p>Read-only request-forgalom a Supabase Management API-ból. A service-role kulcsot ez a modul nem használja.</p>
<section class="status"><div><span>Projekt</span><strong id="project">Betöltés…</strong></div><div><span>Jogosultság</span><strong>analytics_usage_read</strong></div><div><span>Token</span><strong id="configured">—</strong></div><div><span>Validálás</span><strong id="validated">—</strong></div></section>
<section class="card"><h2>1. Scoped / fine-grained Management API token</h2><p>Hozz létre külön monitoring tokent kizárólag a DIMPRO Supabase projekthez, <strong>Usage Analytics · Read</strong> jogosultsággal (<code>analytics_usage_read</code>).</p><div class="callout"><strong>Classic token TILTVA.</strong> A scoped token <code>sbp_fc…</code> kezdetű. Ha a Supabase tokenkészítőben nem jelenik meg projekt- és jogosultságválasztás, a scoped token funkció még nincs engedélyezve a fiókodon; ilyenkor ne generálj classic tokent.</div><a class="button" href="https://supabase.com/dashboard/account/tokens" target="_blank" rel="noreferrer">Supabase tokenkezelő megnyitása ↗</a></section>
<form id="form" class="card"><h2>2. Ellenőrzés és biztonságos mentés</h2><p>A token HTTPS-en kerül a DEV backendhez. Mentés előtt a rendszer ellenőrzi az analytics_usage_read hozzáférést és azt is, hogy egy ettől független Project Settings Read végpont <strong>tiltott</strong> marad-e. Csak least-privilege scoped token menthető.</p><label class="field"><span>Supabase scoped Management API token</span><input id="token" name="supabase_scoped_monitoring_token" type="password" autocomplete="new-password" data-lpignore="true" data-1p-ignore="true" spellcheck="false" placeholder="sbp_fc…"></label><div id="tokencheck" class="tokencheck">Nincs token beillesztve.</div><div class="actions"><button id="save" type="submit" disabled>ELLENŐRZÉS ÉS MENTÉS</button><button id="refresh" type="button" class="secondary">ÁLLAPOT FRISSÍTÉSE</button><button id="remove" type="button" class="danger" hidden>HELYI TOKEN TÖRLÉSE</button></div><div id="authhelp" class="authhelp"><strong>BENJADMIN admin hitelesítés szükséges.</strong><p>Nyisd meg ugyanebben a böngészőprofilban a BENJADMIN admint, jelentkezz be, majd térj vissza és kattints az ÁLLAPOT FRISSÍTÉSE gombra.</p><a class="button secondary" href="/admin" target="_blank" rel="noreferrer">BENJADMIN admin megnyitása ↗</a></div><p id="message" class="message"></p><p id="error" class="error"></p></form>
<section class="card small"><strong>Forgalmi értelmezés</strong><p>Az API / REST / Auth / Storage / Realtime kérésdarabszám automatikusan mérhető. A számlázási egress szervezeti szintű mutató, ezért azt nem becsüljük a request-számokból. Csak hiteles egress usage adat kerül százalékos kvótaként a System Healthbe.</p></section>
</main><script>
const $=id=>document.getElementById(id); const key=()=>localStorage.getItem('dimproLicenseAdminKey')?.trim()||''; const headers=(json=false)=>Object.assign(json?{'content-type':'application/json'}:{},{'x-dimpro-license-admin-key':key()});
function classifyToken(){const v=$('token').value.trim();const ok=v.startsWith('sbp_fc');$('save').disabled=!ok;$('tokencheck').textContent=!v?'Nincs token beillesztve.':ok?'SCOPED TOKEN FELISMERHETŐ · mentés előtt a jogosultságokat is ellenőrizzük.':'CLASSIC / NEM ENGEDÉLYEZETT TOKEN · csak sbp_fc… scoped token használható.';$('tokencheck').className='tokencheck '+(!v?'':ok?'ok':'bad');}
function authProblem(show){$('authhelp').classList.toggle('is-visible',Boolean(show));}
function showStatus(s){$('project').textContent=s?.projectRef||'NINCS';$('configured').textContent=s?.configured?'KONFIGURÁLVA':'NINCS';$('configured').className=s?.configured?'ok':'warn';$('validated').textContent=s?.lastValidatedAt?new Date(s.lastValidatedAt).toLocaleString('hu-HU'):'—';$('remove').hidden=!s?.configured;}
async function refresh(){ $('error').textContent='';authProblem(false); if(!key()){ $('error').textContent='BENJADMIN admin hitelesítés szükséges.';authProblem(true); return; } try{const r=await fetch('/api/dev/grid/supabase-monitoring',{headers:headers(),cache:'no-store'});const p=await r.json();if(!r.ok||!p.status){if(r.status===401)authProblem(true);throw new Error(p.error||'Az állapot nem tölthető be.');}showStatus(p.status);}catch(e){$('error').textContent=e.message||String(e);}}
$('form').addEventListener('submit',async e=>{e.preventDefault();$('error').textContent='';$('message').textContent='';const token=$('token').value.trim();if(!token.startsWith('sbp_fc')){$('error').textContent='Csak sbp_fc… kezdetű scoped/fine-grained token engedélyezett.';return;}$('save').disabled=true;try{const r=await fetch('/api/dev/grid/supabase-monitoring',{method:'POST',headers:headers(true),body:JSON.stringify({token})});const p=await r.json();if(!r.ok||!p.status)throw new Error(p.error||'A token ellenőrzése sikertelen.');$('token').value='';classifyToken();showStatus(p.status);$('message').textContent='Kapcsolat ellenőrizve és biztonságosan mentve. A Developer Gridben nyomj System Health frissítést.';}catch(e){$('error').textContent=e.message||String(e);}finally{$('save').disabled=false;}});
$('token').addEventListener('input',classifyToken);$('refresh').addEventListener('click',refresh);$('remove').addEventListener('click',async()=>{if(!confirm('Törlöd a DEV szerveren tárolt monitoring tokent? A Supabase-fiók tokenje ettől nem kerül visszavonásra.'))return;try{const r=await fetch('/api/dev/grid/supabase-monitoring',{method:'DELETE',headers:headers()});const p=await r.json();if(!r.ok||!p.status)throw new Error(p.error||'A helyi token nem törölhető.');showStatus(p.status);$('message').textContent='A helyi monitoring token törölve.';}catch(e){$('error').textContent=e.message||String(e);}});classifyToken();void refresh();
</script></body></html>`;

export async function GET() {
  return new Response(html, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "x-frame-options": "DENY",
      "content-security-policy": "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; img-src 'none'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",
    },
  });
}
