"use client";

import { AlertTriangle, CheckCircle2, Database, DoorOpen, FileWarning, Flame, Gauge, Layers3, Ruler, ShieldCheck } from "lucide-react";
import { getEnergySettingsReadiness, type EnergyProjectSettings } from "@/components/energy/domain/energyProjectTypes";
import type { EnergyEnvelopeGeometryResult } from "@/components/energy/domain/energyGeometryTypes";
import type { EnergyAssemblySetResult } from "@/components/energy/domain/energyAssemblyTypes";
import type { EnergyZoneSetResult } from "@/components/energy/domain/energyZoneTypes";
import type { EnergyOpeningSetResult } from "@/components/energy/domain/energyOpeningTypes";
import type { EnergyDemandSetResult } from "@/components/energy/domain/energyDemandTypes";
import { getEnergyRuleSet } from "@/components/energy/regulations/registry";
import { DEVELOPMENT_MATERIAL_CATALOG_VERSION, genericMaterialCatalog } from "@/components/materials/catalog/genericMaterialCatalog";

export function EnergyCompliancePanel({ settings, geometry, assemblySet, zoneSet, openingSet, demandSet }: { settings: EnergyProjectSettings; geometry: EnergyEnvelopeGeometryResult; assemblySet: EnergyAssemblySetResult; zoneSet: EnergyZoneSetResult; openingSet: EnergyOpeningSetResult; demandSet: EnergyDemandSetResult }) {
  const readiness = getEnergySettingsReadiness(settings);
  const ruleSet = getEnergyRuleSet(settings.ruleSetId);
  const geometryErrors = geometry.validationMessages.filter((message) => message.severity === "error").length;
  const geometryWarnings = geometry.validationMessages.filter((message) => message.severity === "warning").length;
  const assemblyReady = assemblySet.totals.assemblyCount > 0 && assemblySet.totals.blockedCount === 0;
  const zoneReady = zoneSet.valid;
  const openingReady = openingSet.valid;
  const demandReady = !demandSet.enabled || demandSet.valid;
  return <section className="grid gap-4" data-energy-compliance-panel="true" data-energy-ready={readiness.ready && geometry.valid && assemblyReady && zoneReady && openingReady && demandReady ? "true" : "false"}>
    <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-950" data-energy-disclaimer="true"><div className="flex items-start gap-3"><FileWarning size={22} className="mt-0.5 shrink-0" /><div><div className="text-sm font-black">Tervezői energetikai számítás – szakmai ellenőrzés szükséges</div><p className="mt-1 text-xs font-semibold leading-5">A v0.7.5 ellenőrzött geometriát, zónásítást, rétegrendi és nyílászáró-hőtechnikát, dokumentált hőhidakat, zónánkénti méretezési fűtési terhelést és rendszerkapacitás-ellenőrzést készít. Havi vagy éves energiaigényt, primerenergiát, CO₂-t, referenciaépületet és hiteles tanúsítási végeredményt még nem állít elő.</p></div></div></div>
    <div className="grid grid-cols-2 gap-3">
      <div className="rounded-2xl border border-[var(--survey-border)] bg-[var(--survey-panel-strong)] p-4"><div className="text-[9px] font-black uppercase text-[var(--survey-muted)]">Beállítási készültség</div><div className="mt-2 text-3xl font-black text-[var(--survey-text)]" data-energy-readiness-percent>{readiness.percent}%</div></div>
      <div className={`rounded-2xl border p-4 ${geometry.valid ? "border-emerald-300 bg-emerald-50 text-emerald-950" : "border-rose-300 bg-rose-50 text-rose-950"}`} data-energy-geometry-status="true"><div className="text-[9px] font-black uppercase">Geometria</div><div className="mt-2 text-3xl font-black">{geometry.valid ? "Rendben" : "Blokkolt"}</div><div className="mt-1 text-[9px] font-bold">{geometryErrors} hiba · {geometryWarnings} figyelmeztetés</div></div>
    </div>
    <div className="rounded-2xl border border-emerald-300 bg-emerald-50 p-4 text-emerald-950" data-energy-geometry-engine-card="true"><div className="flex items-start gap-3"><Ruler size={22} className="shrink-0" /><div><div className="text-sm font-black">Geometriamotor {geometry.engineVersion}</div><p className="mt-1 text-xs font-semibold leading-5">Lehűlő felület: {geometry.totals.thermalEnvelopeAreaSquareMeters.toLocaleString("hu-HU")} m² · Kondicionált térfogat: {geometry.totals.conditionedVolumeCubicMeters.toLocaleString("hu-HU")} m³ · Auditált sor: {geometry.trace.length}.</p></div></div></div>
    <div className={`rounded-2xl border p-4 ${assemblyReady ? "border-emerald-300 bg-emerald-50 text-emerald-950" : "border-rose-300 bg-rose-50 text-rose-950"}`} data-energy-assembly-engine-card="true"><div className="flex items-start gap-3"><Layers3 size={22} className="shrink-0" /><div><div className="text-sm font-black">Rétegrend- és U-érték motor {assemblySet.engineVersion}</div><p className="mt-1 text-xs font-semibold leading-5">{assemblySet.totals.assemblyCount} rétegrend · {assemblySet.totals.validCount} számítható · {assemblySet.totals.blockedCount} blokkolt · {assemblySet.totals.compliantCount} megfelelő · {assemblySet.totals.notCompliantCount} nem megfelelő.</p></div></div></div>
    <div className={`rounded-2xl border p-4 ${zoneReady ? "border-emerald-300 bg-emerald-50 text-emerald-950" : "border-rose-300 bg-rose-50 text-rose-950"}`} data-energy-zone-engine-card="true"><div className="flex items-start gap-3"><Flame size={22} className="shrink-0" /><div><div className="text-sm font-black">Zónamotor {zoneSet.engineVersion}</div><p className="mt-1 text-xs font-semibold leading-5">{zoneSet.totals.zoneCount} zóna · {zoneSet.totals.assignedConditionedRoomCount} fűtött helyiség · {zoneSet.totals.unheatedSpaceCount} fűtetlen tér · {zoneSet.validationMessages.filter((message) => message.blocking).length} blokkoló hiba.</p></div></div></div>
    <div className={`rounded-2xl border p-4 ${openingReady ? "border-emerald-300 bg-emerald-50 text-emerald-950" : "border-rose-300 bg-rose-50 text-rose-950"}`} data-energy-opening-engine-card="true"><div className="flex items-start gap-3"><DoorOpen size={22} className="shrink-0" /><div><div className="text-sm font-black">Nyílászáró- és hőhídmotor {openingSet.engineVersion}</div><p className="mt-1 text-xs font-semibold leading-5">{openingSet.totals.openingCount} nyílászáró · {openingSet.totals.validOpeningCount} számítható · {openingSet.totals.blockedOpeningCount} blokkolt · {openingSet.thermalBridges.length} külön hőhíd · H összesen {openingSet.totals.totalHeatLossCoefficientWK.toLocaleString("hu-HU")} W/K.</p></div></div></div>
    <div className={`rounded-2xl border p-4 ${demandReady ? "border-emerald-300 bg-emerald-50 text-emerald-950" : "border-rose-300 bg-rose-50 text-rose-950"}`} data-energy-demand-engine-card="true"><div className="flex items-start gap-3"><Gauge size={22} className="shrink-0" /><div><div className="text-sm font-black">Zónaterhelési motor {demandSet.engineVersion}</div><p className="mt-1 text-xs font-semibold leading-5">{demandSet.enabled ? `${demandSet.totals.zoneCount} zóna · ${demandSet.totals.calculatedZoneCount} számított · ${demandSet.totals.blockedZoneCount} blokkolt · H összesen ${demandSet.totals.totalHeatLossCoefficientWK.toLocaleString("hu-HU")} W/K · fűtési igény ${demandSet.totals.designHeatingPowerKw === null ? "nincs" : `${demandSet.totals.designHeatingPowerKw.toLocaleString("hu-HU")} kW`}` : "A zónaterhelési réteg nincs bekapcsolva; ez régi projektnél nem blokkoló állapot."}</p></div></div></div>
    <div className="rounded-2xl border border-cyan-300 bg-cyan-50 p-4 text-cyan-950" data-energy-rule-set-card="true"><div className="flex items-start gap-3"><ShieldCheck size={22} className="shrink-0" /><div><div className="text-sm font-black">{ruleSet.metadata.id}</div><div className="mt-1 text-xs font-semibold leading-5">{ruleSet.metadata.name}</div><div className="mt-2 inline-flex rounded-full border border-cyan-300 bg-white px-2 py-1 text-[9px] font-black uppercase">{ruleSet.metadata.status} · {ruleSet.metadata.version}</div></div></div></div>
    <div className="rounded-2xl border border-violet-300 bg-violet-50 p-4 text-violet-950" data-energy-material-foundation="true"><div className="flex items-start gap-3"><Database size={22} className="shrink-0" /><div><div className="text-sm font-black">Anyagkatalógus és rétegrendi választó</div><p className="mt-1 text-xs font-semibold leading-5">{genericMaterialCatalog.length} belső fejlesztési tesztanyag · {DEVELOPMENT_MATERIAL_CATALOG_VERSION}. A tesztadatok nem publikálhatók és csak figyelmeztetéssel választhatók rétegrendbe.</p></div></div></div>
    <div className="grid gap-2" data-energy-validation-list="true">
      {readiness.messages.length ? readiness.messages.map((message) => <div key={message.code} data-energy-validation-code={message.code} className={`flex items-start gap-3 rounded-xl border p-3 text-xs font-bold leading-5 ${message.severity === "error" ? "border-rose-300 bg-rose-50 text-rose-950" : message.severity === "warning" ? "border-amber-300 bg-amber-50 text-amber-950" : "border-blue-300 bg-blue-50 text-blue-950"}`}><AlertTriangle size={17} className="mt-0.5 shrink-0" /><span>{message.message}</span></div>) : <div className="flex items-start gap-3 rounded-xl border border-emerald-300 bg-emerald-50 p-3 text-xs font-bold text-emerald-950"><CheckCircle2 size={17} className="shrink-0" /> Az energetikai projektbeállítások kitöltöttek.</div>}
    </div>
    <div className="rounded-xl border border-dashed border-[var(--survey-border)] p-3 text-xs font-semibold leading-5 text-[var(--survey-muted)]">Következő számítási szint: havi nettó fűtési és hűtési energiaigény meteorológiai, szoláris, belső nyereség-, hőtárolási és nyereségkihasználási adatokkal. A teljes energetikai végeredményhez további rendszer-veszteségi és primerenergia-szintek szükségesek.</div>
  </section>;
}
