-- DIMPRO Projektkapu / DRIVE Core 0.3.0
-- Idempotens Supabase/PostgreSQL séma a projektmappákhoz, dokumentumverziókhoz és kézi desktop szinkronhoz.
begin;

create table if not exists public.drive_core_schema_meta (
  component text primary key,
  schema_version text not null,
  migration_count integer not null default 0,
  bootstrap_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.drive_core_folders (
  id text primary key,
  project_id text not null references public.project_core_projects(id) on delete cascade,
  parent_id text null references public.drive_core_folders(id) on delete restrict,
  name text not null,
  path text not null,
  sort_order integer not null default 100,
  status text not null default 'ACTIVE',
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drive_core_folders_name_check check (length(btrim(name)) between 1 and 120 and name !~ '[\\/]'),
  constraint drive_core_folders_path_check check (length(btrim(path)) between 1 and 1200),
  constraint drive_core_folders_status_check check (status in ('ACTIVE','ARCHIVED')),
  constraint drive_core_folders_sort_check check (sort_order between 0 and 999999),
  constraint drive_core_folders_parent_self_check check (parent_id is null or parent_id <> id),
  constraint drive_core_folders_project_path_unique unique (project_id, path)
);

create table if not exists public.drive_core_documents (
  id text primary key,
  project_id text not null references public.project_core_projects(id) on delete cascade,
  folder_id text not null references public.drive_core_folders(id) on delete restrict,
  name text not null,
  extension text not null default '',
  mime_type text not null default 'application/octet-stream',
  description text not null default '',
  status text not null default 'ACTIVE',
  source text not null default 'WEB',
  current_version_number integer not null default 0,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drive_core_documents_name_check check (length(btrim(name)) between 1 and 240 and name !~ '[\\/]'),
  constraint drive_core_documents_status_check check (status in ('ACTIVE','ARCHIVED','DELETED')),
  constraint drive_core_documents_source_check check (source in ('WEB','DESKTOP','DROP','SYSTEM')),
  constraint drive_core_documents_version_check check (current_version_number >= 0)
);

create table if not exists public.drive_core_document_versions (
  id text primary key,
  project_id text not null references public.project_core_projects(id) on delete cascade,
  document_id text not null references public.drive_core_documents(id) on delete cascade,
  version_number integer not null,
  revision_code text not null default '',
  original_name text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0,
  sha256 text null,
  storage_provider text not null default 'METADATA_ONLY',
  storage_bucket text null,
  storage_key text null,
  status text not null default 'METADATA_ONLY',
  change_note text not null default '',
  created_by text not null,
  created_at timestamptz not null default now(),
  constraint drive_core_versions_number_check check (version_number > 0),
  constraint drive_core_versions_size_check check (size_bytes >= 0),
  constraint drive_core_versions_sha_check check (sha256 is null or sha256 ~ '^[a-f0-9]{64}$'),
  constraint drive_core_versions_provider_check check (storage_provider in ('METADATA_ONLY','LOCAL_PREVIEW','S3')),
  constraint drive_core_versions_status_check check (status in ('METADATA_ONLY','STAGED','AVAILABLE','QUARANTINED','REJECTED')),
  constraint drive_core_versions_document_number_unique unique (document_id, version_number)
);

create table if not exists public.drive_core_change_events (
  sequence bigint generated by default as identity primary key,
  id text not null unique,
  project_id text not null references public.project_core_projects(id) on delete cascade,
  event_type text not null,
  entity_type text not null,
  entity_id text not null,
  payload jsonb not null default '{}'::jsonb,
  actor_user_id text not null,
  created_at timestamptz not null default now(),
  constraint drive_core_changes_entity_type_check check (entity_type in ('folder','document','document_version','sync'))
);

create table if not exists public.drive_core_sync_cursors (
  id text primary key,
  project_id text not null references public.project_core_projects(id) on delete cascade,
  client_id text not null,
  machine_name text null,
  cursor_value bigint not null default 0,
  last_sync_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drive_core_sync_cursor_value_check check (cursor_value >= 0),
  constraint drive_core_sync_project_client_unique unique (project_id, client_id)
);

create table if not exists public.drive_core_project_bootstraps (
  project_id text primary key references public.project_core_projects(id) on delete cascade,
  bootstrap_id text not null,
  folder_count integer not null default 0,
  bootstrapped_by text not null,
  bootstrapped_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists drive_core_folders_project_parent_idx on public.drive_core_folders (project_id, parent_id, sort_order, name);
create unique index if not exists drive_core_folders_active_name_unique
  on public.drive_core_folders (project_id, coalesce(parent_id,''), lower(name)) where status = 'ACTIVE';
create index if not exists drive_core_documents_project_folder_idx on public.drive_core_documents (project_id, folder_id, status, updated_at desc);
create unique index if not exists drive_core_documents_active_name_unique
  on public.drive_core_documents (project_id, folder_id, lower(name)) where status = 'ACTIVE';
create index if not exists drive_core_documents_updated_idx on public.drive_core_documents (project_id, updated_at desc);
create index if not exists drive_core_versions_project_document_idx on public.drive_core_document_versions (project_id, document_id, version_number desc);
create unique index if not exists drive_core_versions_storage_key_unique
  on public.drive_core_document_versions (storage_provider, storage_bucket, storage_key) where storage_key is not null;
create index if not exists drive_core_changes_project_sequence_idx on public.drive_core_change_events (project_id, sequence);
create index if not exists drive_core_sync_project_updated_idx on public.drive_core_sync_cursors (project_id, updated_at desc);

alter table public.drive_core_schema_meta enable row level security;
alter table public.drive_core_folders enable row level security;
alter table public.drive_core_documents enable row level security;
alter table public.drive_core_document_versions enable row level security;
alter table public.drive_core_change_events enable row level security;
alter table public.drive_core_sync_cursors enable row level security;
alter table public.drive_core_project_bootstraps enable row level security;

revoke all on public.drive_core_schema_meta from anon, authenticated;
revoke all on public.drive_core_folders from anon, authenticated;
revoke all on public.drive_core_documents from anon, authenticated;
revoke all on public.drive_core_document_versions from anon, authenticated;
revoke all on public.drive_core_change_events from anon, authenticated;
revoke all on public.drive_core_sync_cursors from anon, authenticated;
revoke all on public.drive_core_project_bootstraps from anon, authenticated;

-- A közös projektaudit a DRIVE objektumtípusokat is fogadja.
alter table public.project_core_audit_events drop constraint if exists project_core_audit_entity_type_check;
alter table public.project_core_audit_events add constraint project_core_audit_entity_type_check
  check (entity_type in ('project','membership','lifecycle','folder','document','document_version','sync'));

create or replace function public.drive_core_create_folder_atomic(
  p_project_id text,
  p_folder jsonb,
  p_actor_user_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_folder public.drive_core_folders;
  v_parent public.drive_core_folders;
  v_path text;
begin
  if not exists (select 1 from public.project_core_projects where id = p_project_id and status <> 'DELETED') then
    raise exception 'DRIVE_CORE_PROJECT_NOT_FOUND' using errcode = 'P0002';
  end if;

  if nullif(p_folder->>'parent_id','') is not null then
    select * into v_parent from public.drive_core_folders
      where id = p_folder->>'parent_id' and project_id = p_project_id and status = 'ACTIVE';
    if v_parent.id is null then
      raise exception 'DRIVE_CORE_PARENT_NOT_FOUND' using errcode = 'P0002';
    end if;
    v_path := v_parent.path || '/' || btrim(p_folder->>'name');
  else
    v_path := btrim(p_folder->>'name');
  end if;

  insert into public.drive_core_folders (
    id, project_id, parent_id, name, path, sort_order, status, created_by, created_at, updated_at
  ) values (
    p_folder->>'id', p_project_id, nullif(p_folder->>'parent_id',''), btrim(p_folder->>'name'), v_path,
    coalesce((p_folder->>'sort_order')::integer,100), 'ACTIVE', p_actor_user_id, now(), now()
  ) returning * into v_folder;

  insert into public.project_core_audit_events (
    id, project_id, actor_user_id, event_type, entity_type, entity_id, summary, metadata
  ) values (
    'project-audit-' || substr(replace(gen_random_uuid()::text,'-',''),1,12), p_project_id, p_actor_user_id,
    'DRIVE_FOLDER_CREATED','folder',v_folder.id,'DRIVE mappa létrehozva: ' || v_folder.path,
    jsonb_build_object('path',v_folder.path,'parentId',v_folder.parent_id)
  );

  insert into public.drive_core_change_events (id, project_id, event_type, entity_type, entity_id, payload, actor_user_id)
  values ('drive-change-' || substr(replace(gen_random_uuid()::text,'-',''),1,16), p_project_id,
    'FOLDER_CREATED','folder',v_folder.id,to_jsonb(v_folder),p_actor_user_id);

  return to_jsonb(v_folder);
end;
$$;

create or replace function public.drive_core_create_document_atomic(
  p_project_id text,
  p_document jsonb,
  p_version jsonb,
  p_actor_user_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_document public.drive_core_documents;
  v_version public.drive_core_document_versions;
begin
  if not exists (
    select 1 from public.drive_core_folders
    where id = p_document->>'folder_id' and project_id = p_project_id and status = 'ACTIVE'
  ) then
    raise exception 'DRIVE_CORE_FOLDER_NOT_FOUND' using errcode = 'P0002';
  end if;

  insert into public.drive_core_documents (
    id, project_id, folder_id, name, extension, mime_type, description, status, source,
    current_version_number, created_by, created_at, updated_at
  ) values (
    p_document->>'id', p_project_id, p_document->>'folder_id', p_document->>'name',
    coalesce(p_document->>'extension',''), coalesce(p_document->>'mime_type','application/octet-stream'),
    coalesce(p_document->>'description',''), 'ACTIVE', coalesce(p_document->>'source','WEB'),
    1, p_actor_user_id, coalesce(nullif(p_document->>'created_at','')::timestamptz,now()),
    coalesce(nullif(p_document->>'updated_at','')::timestamptz,now())
  ) returning * into v_document;

  insert into public.drive_core_document_versions (
    id, project_id, document_id, version_number, revision_code, original_name, mime_type, size_bytes,
    sha256, storage_provider, storage_bucket, storage_key, status, change_note, created_by, created_at
  ) values (
    p_version->>'id', p_project_id, v_document.id, 1, coalesce(p_version->>'revision_code','V1'),
    p_version->>'original_name', coalesce(p_version->>'mime_type',v_document.mime_type),
    coalesce((p_version->>'size_bytes')::bigint,0), nullif(p_version->>'sha256',''),
    'METADATA_ONLY', null, null, 'METADATA_ONLY', coalesce(p_version->>'change_note',''),
    p_actor_user_id, coalesce(nullif(p_version->>'created_at','')::timestamptz,now())
  ) returning * into v_version;

  insert into public.project_core_audit_events (
    id, project_id, actor_user_id, event_type, entity_type, entity_id, summary, metadata
  ) values (
    'project-audit-' || substr(replace(gen_random_uuid()::text,'-',''),1,12), p_project_id, p_actor_user_id,
    'DRIVE_DOCUMENT_CREATED','document',v_document.id,'DRIVE dokumentum létrehozva: ' || v_document.name,
    jsonb_build_object('folderId',v_document.folder_id,'version',1,'storageMode','METADATA_ONLY')
  );

  insert into public.drive_core_change_events (id, project_id, event_type, entity_type, entity_id, payload, actor_user_id)
  values ('drive-change-' || substr(replace(gen_random_uuid()::text,'-',''),1,16), p_project_id,
    'DOCUMENT_CREATED','document',v_document.id,
    jsonb_build_object('document',to_jsonb(v_document),'version',to_jsonb(v_version)),p_actor_user_id);

  return jsonb_build_object('document',to_jsonb(v_document),'version',to_jsonb(v_version));
end;
$$;

create or replace function public.drive_core_add_version_atomic(
  p_project_id text,
  p_document_id text,
  p_version jsonb,
  p_actor_user_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_document public.drive_core_documents;
  v_version public.drive_core_document_versions;
  v_expected integer;
  v_next integer;
begin
  select * into v_document from public.drive_core_documents
    where id = p_document_id and project_id = p_project_id and status = 'ACTIVE' for update;
  if v_document.id is null then
    raise exception 'DRIVE_CORE_DOCUMENT_NOT_FOUND' using errcode = 'P0002';
  end if;

  v_expected := coalesce((p_version->>'expected_current_version')::integer,0);
  if v_expected > 0 and v_expected <> v_document.current_version_number then
    raise exception 'DRIVE_CORE_VERSION_CONFLICT' using errcode = 'P0001';
  end if;
  v_next := v_document.current_version_number + 1;

  insert into public.drive_core_document_versions (
    id, project_id, document_id, version_number, revision_code, original_name, mime_type, size_bytes,
    sha256, storage_provider, storage_bucket, storage_key, status, change_note, created_by, created_at
  ) values (
    p_version->>'id', p_project_id, p_document_id, v_next,
    coalesce(nullif(p_version->>'revision_code',''),'V' || v_next::text), p_version->>'original_name',
    coalesce(p_version->>'mime_type',v_document.mime_type), coalesce((p_version->>'size_bytes')::bigint,0),
    nullif(p_version->>'sha256',''), 'METADATA_ONLY', null, null, 'METADATA_ONLY',
    coalesce(p_version->>'change_note',''), p_actor_user_id,
    coalesce(nullif(p_version->>'created_at','')::timestamptz,now())
  ) returning * into v_version;

  update public.drive_core_documents
  set current_version_number = v_next,
      mime_type = v_version.mime_type,
      updated_at = now()
  where id = p_document_id
  returning * into v_document;

  insert into public.project_core_audit_events (
    id, project_id, actor_user_id, event_type, entity_type, entity_id, summary, metadata
  ) values (
    'project-audit-' || substr(replace(gen_random_uuid()::text,'-',''),1,12), p_project_id, p_actor_user_id,
    'DRIVE_DOCUMENT_VERSION_CREATED','document_version',v_version.id,
    'Új DRIVE dokumentumverzió: ' || v_document.name || ' · V' || v_next::text,
    jsonb_build_object('documentId',v_document.id,'version',v_next,'storageMode','METADATA_ONLY')
  );

  insert into public.drive_core_change_events (id, project_id, event_type, entity_type, entity_id, payload, actor_user_id)
  values ('drive-change-' || substr(replace(gen_random_uuid()::text,'-',''),1,16), p_project_id,
    'DOCUMENT_VERSION_CREATED','document_version',v_version.id,
    jsonb_build_object('document',to_jsonb(v_document),'version',to_jsonb(v_version)),p_actor_user_id);

  return jsonb_build_object('document',to_jsonb(v_document),'version',to_jsonb(v_version));
end;
$$;

create or replace function public.drive_core_upsert_sync_cursor(
  p_project_id text,
  p_client_id text,
  p_machine_name text,
  p_cursor_value bigint,
  p_metadata jsonb,
  p_actor_user_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cursor public.drive_core_sync_cursors;
  v_id text;
begin
  if not exists (select 1 from public.project_core_projects where id = p_project_id and status <> 'DELETED') then
    raise exception 'DRIVE_CORE_PROJECT_NOT_FOUND' using errcode = 'P0002';
  end if;
  v_id := 'drive-sync-' || substr(md5(p_project_id || ':' || p_client_id),1,20);
  insert into public.drive_core_sync_cursors (
    id, project_id, client_id, machine_name, cursor_value, last_sync_at, metadata, created_at, updated_at
  ) values (
    v_id, p_project_id, p_client_id, nullif(p_machine_name,''), greatest(p_cursor_value,0), now(),
    coalesce(p_metadata,'{}'::jsonb), now(), now()
  )
  on conflict (project_id, client_id) do update set
    machine_name = coalesce(excluded.machine_name,public.drive_core_sync_cursors.machine_name),
    cursor_value = greatest(public.drive_core_sync_cursors.cursor_value,excluded.cursor_value),
    last_sync_at = now(), metadata = excluded.metadata, updated_at = now()
  returning * into v_cursor;

  insert into public.drive_core_change_events (id, project_id, event_type, entity_type, entity_id, payload, actor_user_id)
  values ('drive-change-' || substr(replace(gen_random_uuid()::text,'-',''),1,16), p_project_id,
    'SYNC_CURSOR_UPDATED','sync',v_cursor.id,
    jsonb_build_object('clientId',v_cursor.client_id,'cursorValue',v_cursor.cursor_value,'machineName',v_cursor.machine_name),p_actor_user_id);
  return to_jsonb(v_cursor);
end;
$$;

create or replace function public.drive_core_bootstrap_project(
  p_project_id text,
  p_actor_user_id text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.drive_core_project_bootstraps;
  v_item record;
  v_parent_id text;
  v_folder_id text;
  v_inserted integer := 0;
  v_row_count integer;
begin
  if not exists (select 1 from public.project_core_projects where id = p_project_id and status <> 'DELETED') then
    raise exception 'DRIVE_CORE_PROJECT_NOT_FOUND' using errcode = 'P0002';
  end if;
  select * into v_existing from public.drive_core_project_bootstraps where project_id = p_project_id for update;
  if v_existing.project_id is not null then
    return jsonb_build_object('projectId',p_project_id,'folders',v_existing.folder_count,'alreadyBootstrapped',true);
  end if;

  for v_item in select * from (values
    ('01_Tervek',10),('02_Muszaki_dokumentumok',20),('03_Penzugy',30),('04_Szerzodesek',40),
    ('05_Jegyzokonyvek',50),('06_Atadas',60),('99_Archivum',990)
  ) as seed(name,sort_order) loop
    v_folder_id := 'drive-folder-' || substr(md5(p_project_id || ':' || v_item.name),1,20);
    insert into public.drive_core_folders (id,project_id,parent_id,name,path,sort_order,status,created_by)
    values (v_folder_id,p_project_id,null,v_item.name,v_item.name,v_item.sort_order,'ACTIVE',p_actor_user_id)
    on conflict (project_id,path) do nothing;
    get diagnostics v_row_count = row_count;
    v_inserted := v_inserted + v_row_count;
  end loop;

  select id into v_parent_id from public.drive_core_folders where project_id = p_project_id and path = '01_Tervek';
  for v_item in select * from (values ('Epiteszet',10),('Gepeszet',20),('Elektromos',30)) as seed(name,sort_order) loop
    v_folder_id := 'drive-folder-' || substr(md5(p_project_id || ':01_Tervek/' || v_item.name),1,20);
    insert into public.drive_core_folders (id,project_id,parent_id,name,path,sort_order,status,created_by)
    values (v_folder_id,p_project_id,v_parent_id,v_item.name,'01_Tervek/' || v_item.name,v_item.sort_order,'ACTIVE',p_actor_user_id)
    on conflict (project_id,path) do nothing;
    get diagnostics v_row_count = row_count;
    v_inserted := v_inserted + v_row_count;
  end loop;

  insert into public.drive_core_project_bootstraps (project_id,bootstrap_id,folder_count,bootstrapped_by)
  values (p_project_id,'drive-core-v030-20260802',(select count(*) from public.drive_core_folders where project_id=p_project_id),p_actor_user_id);

  insert into public.project_core_audit_events (
    id, project_id, actor_user_id, event_type, entity_type, entity_id, summary, metadata
  ) values (
    'project-audit-' || substr(replace(gen_random_uuid()::text,'-',''),1,12),p_project_id,p_actor_user_id,
    'DRIVE_CORE_BOOTSTRAPPED','project',p_project_id,'A DRIVE Core alapmappái létrejöttek.',
    jsonb_build_object('schemaVersion','0.3.0','insertedFolders',v_inserted)
  );

  insert into public.drive_core_change_events (id,project_id,event_type,entity_type,entity_id,payload,actor_user_id)
  values ('drive-change-' || substr(replace(gen_random_uuid()::text,'-',''),1,16),p_project_id,
    'DRIVE_PROJECT_BOOTSTRAPPED','folder',p_project_id,
    jsonb_build_object('insertedFolders',v_inserted,'schemaVersion','0.3.0'),p_actor_user_id);

  return jsonb_build_object(
    'projectId',p_project_id,
    'folders',(select count(*) from public.drive_core_folders where project_id=p_project_id),
    'insertedFolders',v_inserted,
    'alreadyBootstrapped',false
  );
end;
$$;

revoke all on function public.drive_core_create_folder_atomic(text,jsonb,text) from public, anon, authenticated;
revoke all on function public.drive_core_create_document_atomic(text,jsonb,jsonb,text) from public, anon, authenticated;
revoke all on function public.drive_core_add_version_atomic(text,text,jsonb,text) from public, anon, authenticated;
revoke all on function public.drive_core_upsert_sync_cursor(text,text,text,bigint,jsonb,text) from public, anon, authenticated;
revoke all on function public.drive_core_bootstrap_project(text,text) from public, anon, authenticated;
grant execute on function public.drive_core_create_folder_atomic(text,jsonb,text) to service_role;
grant execute on function public.drive_core_create_document_atomic(text,jsonb,jsonb,text) to service_role;
grant execute on function public.drive_core_add_version_atomic(text,text,jsonb,text) to service_role;
grant execute on function public.drive_core_upsert_sync_cursor(text,text,text,bigint,jsonb,text) to service_role;
grant execute on function public.drive_core_bootstrap_project(text,text) to service_role;

insert into public.drive_core_schema_meta (component,schema_version,migration_count,bootstrap_id,updated_at)
values ('drive-core','0.3.0',1,'drive-core-v030-20260802',now())
on conflict (component) do update set
  schema_version=excluded.schema_version,
  migration_count=excluded.migration_count,
  bootstrap_id=excluded.bootstrap_id,
  updated_at=now();

commit;
