"use client";

import { ArrowDown, ArrowUp, Check, ChevronDown, ChevronUp, Eye, LockKeyhole, Pencil, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import type { MeetingAgendaItem, MeetingTopicBlock, MeetingViewRole, MeetingWorkspace } from "@/app/lib/meeting-assistant/types";

const empty = { id: "", title: "", background: "", discussion: "", decision: "", openQuestions: "", clientOpinion: "", designerOpinion: "", contractorOpinion: "", owner: "", dueDate: "", privateNotes: "", shared: true, previousMeetingId: "", previousAgendaItemId: "", attachmentIds: [] as string[] };

export default function MeetingTopicBlocksEditor({ agendaItem, workspace, role, locked, postWorkspace, setStatus }: { agendaItem: MeetingAgendaItem; workspace: MeetingWorkspace; role: MeetingViewRole; locked: boolean; postWorkspace: (operation: string, payload: Record<string, unknown>) => Promise<MeetingWorkspace>; setStatus: (value: string) => void }) {
  const [form, setForm] = useState(empty);
  const [formOpen, setFormOpen] = useState(false);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [saving, setSaving] = useState(false);
  const topics = agendaItem.topicBlocks.slice().sort((a, b) => a.order - b.order);

  function edit(topic?: MeetingTopicBlock) {
    setForm(topic ? { id: topic.id, title: topic.title, background: topic.background, discussion: topic.discussion, decision: topic.decision, openQuestions: topic.openQuestions, clientOpinion: topic.clientOpinion, designerOpinion: topic.designerOpinion, contractorOpinion: topic.contractorOpinion, owner: topic.owner, dueDate: topic.dueDate, privateNotes: topic.privateNotes, shared: topic.shared, previousMeetingId: topic.previousMeetingId, previousAgendaItemId: topic.previousAgendaItemId, attachmentIds: topic.attachmentIds } : { ...empty, title: `Témakör ${topics.length + 1}` });
    setFormOpen(true);
  }

  async function save() {
    if (!form.title.trim()) { setStatus("A témakör címe kötelező."); return; }
    setSaving(true);
    try { await postWorkspace("upsert_topic_block", { agendaItemId: agendaItem.id, ...form, updatedBy: role === "editor" ? workspace.editorAccess.editorName || "Jegyzőkönyv-szerkesztő" : workspace.minuteTakerName || workspace.organizerName }); setStatus("A témakör mentve."); setFormOpen(false); setForm(empty); }
    catch (error) { setStatus(error instanceof Error ? error.message : "A témakör mentése sikertelen."); }
    finally { setSaving(false); }
  }

  async function remove(topic: MeetingTopicBlock) {
    if (!window.confirm(`Törlöd a témakört: ${topic.title}?`)) return;
    await postWorkspace("remove_topic_block", { agendaItemId: agendaItem.id, topicBlockId: topic.id });
  }

  return (
    <div className="mt-4 border-t border-indigo-200 pt-3">
      <div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-[10px] font-black uppercase tracking-[0.12em] text-indigo-700">Gyors témablokkok</div><div className="text-[9px] text-slate-500">Menet közben egymás után rögzíthető minden felmerülő témakör.</div></div><div className="flex gap-2"><button type="button" onClick={() => edit()} disabled={locked} className="inline-flex items-center gap-1 rounded-md bg-indigo-700 px-3 py-2 text-[9px] font-black text-white"><Plus size={12} /> Új témakör</button>{topics.length > 0 && <button type="button" onClick={() => void postWorkspace("promote_topic_blocks", { agendaItemId: agendaItem.id })} disabled={locked} className="rounded-md border border-indigo-200 px-3 py-2 text-[9px] font-black text-indigo-700">Külön napirendi pontokká</button>}</div></div>
      <div className="mt-2 space-y-1.5">{topics.length === 0 ? <div className="rounded-md border border-dashed p-3 text-center text-[9px] text-slate-500">Még nincs rögzített témakör.</div> : topics.map((topic, index) => { const open = expanded.has(topic.id); return <article key={topic.id} className="rounded-lg border border-slate-200 bg-white"><div className="flex items-center gap-2 px-2 py-2"><button type="button" onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(topic.id)) next.delete(topic.id); else next.add(topic.id); return next; })} className="text-slate-400">{open ? <ChevronUp size={13} /> : <ChevronDown size={13} />}</button><span className="min-w-0 flex-1 truncate text-[10px] font-black">{topic.order}. {topic.title}</span>{topic.decision && <span className="rounded-full bg-emerald-100 px-1.5 py-0.5 text-[7px] font-black text-emerald-700">döntés</span>}{topic.openQuestions && <span className="rounded-full bg-amber-100 px-1.5 py-0.5 text-[7px] font-black text-amber-700">nyitott</span>}{topic.shared ? <Eye size={12} className="text-emerald-600" /> : <LockKeyhole size={12} className="text-slate-500" />}{role === "organizer" && <><button type="button" onClick={() => void postWorkspace("move_topic_block", { agendaItemId: agendaItem.id, topicBlockId: topic.id, direction: "up" })} disabled={index === 0 || locked}><ArrowUp size={11} /></button><button type="button" onClick={() => void postWorkspace("move_topic_block", { agendaItemId: agendaItem.id, topicBlockId: topic.id, direction: "down" })} disabled={index === topics.length - 1 || locked}><ArrowDown size={11} /></button></>}<button type="button" onClick={() => edit(topic)} disabled={locked}><Pencil size={11} /></button><button type="button" onClick={() => void remove(topic)} disabled={locked} className="text-rose-600"><Trash2 size={11} /></button></div>{open && <div className="grid gap-2 border-t bg-slate-50 p-2 text-[9px] sm:grid-cols-2">{[["Előzmény", topic.background], ["Egyeztetés tartalma", topic.discussion], ["Döntés / eredmény", topic.decision], ["Nyitott kérdések", topic.openQuestions], ["Megrendelői vélemény / jóváhagyás", topic.clientOpinion], ["Tervezői álláspont", topic.designerOpinion], ["Kivitelezői álláspont", topic.contractorOpinion]].filter(([, value]) => value).map(([label, value]) => <div key={label} className="rounded-md bg-white p-2"><b>{label}</b><div className="mt-1 whitespace-pre-wrap leading-4 text-slate-600">{value}</div></div>)}{(topic.owner || topic.dueDate) && <div className="rounded-md bg-white p-2"><b>Felelős / határidő</b><div>{topic.owner || "-"} · {topic.dueDate || "-"}</div></div>}</div>}</article>; })}</div>

      {formOpen && <div className="fixed inset-0 z-[15500] flex items-center justify-center bg-slate-950/65 p-2"><div className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-xl bg-white p-4 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="text-sm font-black">{form.id ? "Témakör szerkesztése" : "Új témakör"}</h3><p className="text-[9px] text-slate-500">Csak a kitöltött mezők jelennek meg a dokumentumban.</p></div><button type="button" onClick={() => setFormOpen(false)}><X size={17} /></button></div><div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2"><label className="sm:col-span-2 text-[9px] font-black">Téma címe<input value={form.title} onChange={(e) => setForm((c) => ({ ...c, title: e.target.value }))} className="mt-1 w-full rounded-md border p-2 text-[10px]" /></label>{[["Előzmény / problémafelvetés", "background"], ["Egyeztetés tartalma", "discussion"], ["Döntés / eredmény", "decision"], ["Nyitott kérdések", "openQuestions"], ["Megrendelői vélemény / jóváhagyás", "clientOpinion"], ["Tervezői álláspont", "designerOpinion"], ["Kivitelezői álláspont", "contractorOpinion"], ...(role === "organizer" ? [["Privát szervezői megjegyzés", "privateNotes"]] : [])].map(([label, key]) => <label key={key} className="text-[9px] font-black">{label}<textarea value={String(form[key as keyof typeof form])} onChange={(e) => setForm((c) => ({ ...c, [key]: e.target.value }))} rows={key === "discussion" ? 6 : 3} className="mt-1 w-full rounded-md border p-2 text-[10px] leading-5" /></label>)}<input value={form.owner} onChange={(e) => setForm((c) => ({ ...c, owner: e.target.value }))} placeholder="Felelős" className="rounded-md border p-2 text-[10px]" /><input type="date" value={form.dueDate} onChange={(e) => setForm((c) => ({ ...c, dueDate: e.target.value }))} className="rounded-md border p-2 text-[10px]" /><input value={form.previousMeetingId} onChange={(e) => setForm((c) => ({ ...c, previousMeetingId: e.target.value }))} placeholder="Kapcsolódó korábbi meeting ID" className="rounded-md border p-2 text-[10px]" /><input value={form.previousAgendaItemId} onChange={(e) => setForm((c) => ({ ...c, previousAgendaItemId: e.target.value }))} placeholder="Kapcsolódó korábbi napirendi pont ID" className="rounded-md border p-2 text-[10px]" /></div>{role === "organizer" && <label className="mt-3 flex items-center gap-2 text-[10px] font-bold"><input type="checkbox" checked={form.shared} onChange={(e) => setForm((c) => ({ ...c, shared: e.target.checked }))} /> Résztvevőkkel megosztott témakör</label>}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setFormOpen(false)} className="rounded-md border px-3 py-2 text-[10px] font-black">Mégse</button><button type="button" onClick={() => void save()} disabled={saving} className="inline-flex items-center gap-1 rounded-md bg-indigo-700 px-4 py-2 text-[10px] font-black text-white"><Check size={13} /> Mentés</button></div></div></div>}
    </div>
  );
}
