import type { AruterFeatureFlag, AruterOrder, AruterProduct, AruterRealtimeEvent } from "./types";

export const aruterProducts: AruterProduct[] = [
  {
    id: "prod-001",
    sku: "KERT-TUJA-120",
    name: "Smaragd tuja 120–140 cm",
    category: "Dísznövény",
    template: "kertészet",
    unit: "db",
    priceNet: 5490,
    vatRate: 27,
    stockQuantity: 42,
    storageZone: "Külső árutér / A2 sor",
    barcode: "5990000000011",
    isActive: true,
  },
  {
    id: "prod-002",
    sku: "KERT-MULCS-50",
    name: "Fenyőkéreg mulcs 50 l",
    category: "Talajtakaró",
    template: "kertészet",
    unit: "zsák",
    priceNet: 1890,
    vatRate: 27,
    stockQuantity: 130,
    storageZone: "Raklapos zóna / M1",
    isActive: true,
  },
  {
    id: "prod-003",
    sku: "TUZEP-ZSAKO-CEM-25",
    name: "Cement 25 kg",
    category: "Kötőanyag",
    template: "tüzép",
    unit: "csomag",
    priceNet: 2190,
    vatRate: 27,
    stockQuantity: 86,
    storageZone: "Fedett raktár / C3",
    isActive: true,
  },
  {
    id: "prod-004",
    sku: "HUSB-SERT-LAPOCKA",
    name: "Sertés lapocka",
    category: "Friss hús",
    template: "húsbolt",
    unit: "kg",
    priceNet: 1890,
    vatRate: 5,
    stockQuantity: 24,
    storageZone: "Hűtőpult / H2",
    isActive: true,
  },
];

export const aruterOrders: AruterOrder[] = [
  {
    id: "ord-001",
    orderNumber: "AR-2026-0001",
    template: "kertészet",
    status: "sent_to_cashier",
    customerName: "Helyszíni vásárló",
    customerType: "walk_in",
    recorderName: "Árutéri dolgozó",
    note: "A vevő a pénztárnál fizet, majd az A2 sorból átveheti.",
    createdAt: "2026-06-20T18:10:00.000Z",
    sentToCashierAt: "2026-06-20T18:14:00.000Z",
    items: [
      {
        id: "item-001",
        productId: "prod-001",
        productName: "Smaragd tuja 120–140 cm",
        sku: "KERT-TUJA-120",
        unit: "db",
        quantity: 6,
        priceNet: 5490,
        vatRate: 27,
        storageZone: "Külső árutér / A2 sor",
      },
      {
        id: "item-002",
        productId: "prod-002",
        productName: "Fenyőkéreg mulcs 50 l",
        sku: "KERT-MULCS-50",
        unit: "zsák",
        quantity: 3,
        priceNet: 1890,
        vatRate: 27,
        storageZone: "Raklapos zóna / M1",
      },
    ],
  },
  {
    id: "ord-002",
    orderNumber: "AR-2026-0002",
    template: "húsbolt",
    status: "paid",
    customerName: "Kovács István törzsvásárló",
    customerType: "loyal_customer",
    recorderName: "Pultos dolgozó",
    cashierName: "Pénztáros 1",
    paymentMethod: "card",
    pickupTime: "2026-06-20 18:45",
    createdAt: "2026-06-20T18:20:00.000Z",
    sentToCashierAt: "2026-06-20T18:21:00.000Z",
    paidAt: "2026-06-20T18:24:00.000Z",
    items: [
      {
        id: "item-003",
        productId: "prod-004",
        productName: "Sertés lapocka",
        sku: "HUSB-SERT-LAPOCKA",
        unit: "kg",
        quantity: 2.4,
        priceNet: 1890,
        vatRate: 5,
        storageZone: "Hűtőpult / H2",
      },
    ],
  },
];

export const aruterRealtimeEvents: AruterRealtimeEvent[] = [
  {
    id: "evt-001",
    type: "cart_sent",
    orderId: "ord-001",
    orderNumber: "AR-2026-0001",
    title: "Kosár pénztárra küldve",
    description: "2 tétel, Kertészet sablon, helyszíni vásárló.",
    createdAt: "2026-06-20T18:14:00.000Z",
  },
  {
    id: "evt-002",
    type: "payment_registered",
    orderId: "ord-002",
    orderNumber: "AR-2026-0002",
    title: "Fizetés rögzítve",
    description: "Bankkártyás fizetés, kiadásra vár.",
    createdAt: "2026-06-20T18:24:00.000Z",
  },
];

export const aruterFeatureFlags: AruterFeatureFlag[] = [
  { key: "internal_goods_recorder", label: "Belső árufelvevő", enabledInMvp: true, phase: 1 },
  { key: "cashier_order_queue", label: "Pénztári rendeléskezelő", enabledInMvp: true, phase: 2 },
  { key: "admin_product_manager", label: "Admin termékkezelő", enabledInMvp: true, phase: 3 },
  { key: "loyal_customer_reservation", label: "Törzsvásárlói zárt foglalás", enabledInMvp: false, phase: 4 },
  { key: "public_webshop", label: "Nyilvános webshop", enabledInMvp: false, phase: 5 },
];
