export const dynamic = "force-dynamic";
export const runtime = "nodejs";
const html = `<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BENJADMIN · VPS telemetria</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#07111d;color:#e8f5f4;font:14px system-ui,sans-serif}.shell{max-width:920px;margin:auto;padding:28px}.card{background:#0d1a29;border:1px solid #27404b;border-radius:14px;padding:20px;margin:16px 0}h1{font-size:26px}h2{font-size:17px}p{color:#a8bdc4;line-height:1.55}label{display:block;margin:12px 0}select,input,button{font:inherit;padding:10px;border-radius:8px;border:1px solid #385366;background:#101f2e;color:#e8f5f4}button{cursor:pointer;font-weight:700}button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:10px;flex-wrap:wrap}.ok{color:#68e6b6}.error{color:#ff98a8}.warn{color:#ffd47a}.secret{width:100%;font-family:monospace;overflow-wrap:anywhere}a{color:#68d6ce}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid #27404b}
</style></head><body><main class="shell"><p>BENJADMIN DEVELOPER GRID · DEV ONLY</p><h1>PROD / DB VPS telemetria</h1><p>A mérés kizárólag rendszererőforrásokat olvas. Nem biztosít távoli parancsvégrehajtást, és nem módosít alkalmazást vagy adatbázist.</p><section class="card"><h2>1. Regisztrációs állapot</h2><table><thead><tr><th>Node</th><th>Állapot</th></tr></thead><tbody id="nodes"><tr><td colspan="2">Betöltés…</td></tr></tbody></table><div class="actions"><button type="button" id="refresh">Állapot frissítése</button><a href="/admin" target="_blank" rel="noreferrer">BENJADMIN admin</a></div></section><section class="card"><h2>2. Egyszeri admin-jóváhagyás</h2><p>Csak akkor indítsd, amikor a megfelelő VPS megbízható szolgáltatói konzolján vagy. A kód 10 percig érvényes, egyetlen node-hoz kötött, és csak egyszer használható.</p><form id="arm"><label>VPS <select id="node"><option value="prod-vps">PROD · license.dimpro.hu</option><option value="db-vps">DB · db.dimpro.hu</option></select></label><label><input id="confirm" type="checkbox" style="width:auto"> Megerősítem, hogy a kiválasztott szerver konzolján vagyok.</label><button id="prepare" type="submit">EGYSZERI REGISZTRÁCIÓ ELŐKÉSZÍTÉSE</button></form><div id="approval" hidden><p class="warn">A kód csak most jelenik meg. Ne küldd csevegésbe, és ne add meg parancssori argumentumként.</p><label>Egyszeri kód <input id="code" class="secret" readonly autocomplete="off"></label><p id="expiry"></p><button type="button" id="copy">Kód másolása</button><p>A kódot a telepítő rejtett konzolos kérésébe illeszd be.</p></div><p id="message" class="ok" role="status"></p><p id="error" class="error" role="alert"></p></section><section class="card"><h2>3. Telepítés és ellenőrzés</h2><p>A telepítő ellenőrzött forráscsomagból indul, az első sikeres mintavétel után kapcsolja be a percenkénti systemd timert. A meglévő kulcsot nem írja felül. A PROD és DB telepítése külön történik.</p><p>Először ellenőrizd a szerverazonosságot és a csomag SHA-256 értékét. A pontos parancsokat a kiadási átadó tartalmazza. Sikertelen regisztráció esetén ellenőrizd az állapotot.</p><p>A System Health csak friss, hiteles mintát jelöl LIVE-nak. A régi, 2026. augusztusi snapshot nem használható mai erőforrásmérésként.</p></section></main><script>
const $=id=>document.getElementById(id);const endpoint="/api/dev/grid/protected-telemetry/admin";const key=()=>localStorage.getItem("dimproLicenseAdminKey")?.trim()||"";const headers=()=>({"x-dimpro-license-admin-key":key(),"content-type":"application/json"});
function clearApproval(){$("code").value="";$("approval").hidden=true;$("expiry").textContent="";}
async function refresh(){clearApproval();$("error").textContent="";try{const r=await fetch(endpoint,{headers:headers(),cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(r.status===401?"BENJADMIN admin bejelentkezés szükséges.":"Az állapot nem olvasható.");$("nodes").replaceChildren();for(const n of x.nodes||[]){const tr=document.createElement("tr");const a=document.createElement("td");const b=document.createElement("td");a.textContent=n.nodeId;b.textContent=n.registered?"REGISZTRÁLVA":n.enrollmentPending?"JÓVÁHAGYÁS VÁR · "+new Date(n.expiresAt).toLocaleTimeString("hu-HU"):"NINCS REGISZTRÁCIÓ";tr.append(a,b);$("nodes").append(tr);}}catch(e){$("error").textContent=e.message||String(e);}}
$("refresh").addEventListener("click",refresh);$("node").addEventListener("change",()=>{clearApproval();$("confirm").checked=false;});$("arm").addEventListener("submit",async e=>{e.preventDefault();clearApproval();$("error").textContent="";$("message").textContent="";if(!$("confirm").checked){$("error").textContent="Erősítsd meg a kiválasztott VPS-t.";return;}$("prepare").disabled=true;try{const r=await fetch(endpoint,{method:"POST",headers:headers(),body:JSON.stringify({nodeId:$("node").value,confirm:true})});const x=await r.json();if(!r.ok||!x.approval)throw new Error(x.error||"A jóváhagyás sikertelen.");$("code").value=x.approval.code;$("expiry").textContent="Lejárat: "+new Date(x.approval.expiresAt).toLocaleString("hu-HU");$("approval").hidden=false;$("message").textContent="A kiválasztott node regisztrációja előkészítve.";}catch(e){$("error").textContent=e.message||String(e);}finally{$("prepare").disabled=false;}});$("copy").addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("code").value);$("message").textContent="Kód másolva.";}catch{$("code").select();$("message").textContent="A kód kijelölve, másold ki kézzel.";}});void refresh();
</script></body></html>`;
export async function GET() {
  const q=String.fromCharCode(39);
  return new Response(html,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-frame-options":"DENY","content-security-policy":`default-src ${q}self${q}; style-src ${q}unsafe-inline${q}; script-src ${q}unsafe-inline${q}; connect-src ${q}self${q}; img-src ${q}none${q}; object-src ${q}none${q}; frame-ancestors ${q}none${q}; base-uri ${q}none${q}; form-action ${q}self${q}`}});
}
