import type { SurveyRoom } from "@/components/viewers/SurveyFloorPlanEngine";
import { resolveSurveyRoomDimensions, roundSurveyMeasurement } from "@/components/property-survey/propertySurveyRoomDimensions";

export type SurveyPaperSize = "A4" | "A3" | "A2";
export type SurveyPaperOrientation = "portrait" | "landscape";
export type SurveyScaleMode = "auto" | "manual";
export type SurveyLevelKind = "basement" | "ground" | "floor" | "attic";
export type SurveyWallSide = "top" | "right" | "bottom" | "left";
export type SurveyWallBoundaryType = "external" | "internal" | "unheated" | "ground" | "adjacent";
export type SurveyOpeningKind = "window" | "door" | "balconyDoor" | "garageDoor";

export type SurveyPlanSheetSettings = {
  paperSize: SurveyPaperSize;
  orientation: SurveyPaperOrientation;
  scaleMode: SurveyScaleMode;
  scaleDenominator: number;
};

export type SurveyBuildingLevel = {
  id: string;
  name: string;
  shortName: string;
  kind: SurveyLevelKind;
  order: number;
  elevationMeters: number;
  createdAt: string;
};

export type SurveyPlanTransferredPoint = { x: number; y: number };
export type SurveyModelDataSource = "automatic" | "manual" | "planTransfer";

export type SurveyWallSegment = {
  id: string;
  levelId: string;
  roomId: string;
  side: SurveyWallSide;
  startRatio: number;
  endRatio: number;
  boundaryType: SurveyWallBoundaryType;
  wallType: string;
  thicknessCm: number;
  assemblyId?: string;
  adjacentRoomId?: string;
  note: string;
  isAutoGenerated?: boolean;
  measuredLengthMeters?: number;
  heightMeters?: number;
  orientationDegrees?: number;
  zoneId?: string;
  adjacentZoneId?: string;
  dataSource?: SurveyModelDataSource;
  planPageId?: string;
  planWallSuggestionId?: string;
  planStart?: SurveyPlanTransferredPoint;
  planEnd?: SurveyPlanTransferredPoint;
  planTransferUpdatedAt?: string;
  planTransferLocked?: boolean;
  createdAt: string;
  updatedAt: string;
};

export type SurveyWallOpening = {
  id: string;
  levelId: string;
  roomId: string;
  wallSegmentId: string;
  kind: SurveyOpeningKind;
  name: string;
  widthMeters: number;
  heightMeters: number;
  sillHeightMeters: number;
  offsetRatio: number;
  frame: string;
  glazing: string;
  uValue: string;
  shading: string;
  note: string;
  zoneId?: string;
  catalogProfileId?: string;
  dataSource?: SurveyModelDataSource;
  planPageId?: string;
  planOpeningSuggestionId?: string;
  planTransferUpdatedAt?: string;
  planTransferLocked?: boolean;
  createdAt: string;
  updatedAt: string;
};

export type SurveyWallGeometry = {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  lengthPlanUnits: number;
  lengthMeters: number;
};

export const surveyPaperSizesMm: Record<SurveyPaperSize, { width: number; height: number }> = {
  A4: { width: 210, height: 297 },
  A3: { width: 297, height: 420 },
  A2: { width: 420, height: 594 },
};

export const surveyScaleOptions = [20, 25, 50, 75, 100, 125, 150, 200, 250, 500];

export const surveyWallSideLabels: Record<SurveyWallSide, string> = {
  top: "Felső oldal",
  right: "Jobb oldal",
  bottom: "Alsó oldal",
  left: "Bal oldal",
};

export const surveyWallBoundaryLabels: Record<SurveyWallBoundaryType, string> = {
  external: "Külső levegővel határos",
  internal: "Fűtött helyiségek közötti",
  unheated: "Fűtetlen térrel határos",
  ground: "Talajjal érintkező",
  adjacent: "Szomszédos épület / rendeltetési egység",
};

export const surveyOpeningKindLabels: Record<SurveyOpeningKind, string> = {
  window: "Ablak",
  door: "Ajtó",
  balconyDoor: "Erkélyajtó",
  garageDoor: "Garázskapu",
};

export function createBuildingModelId(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function createGroundLevel(): SurveyBuildingLevel {
  const now = new Date().toISOString();
  return {
    id: "level-ground",
    name: "Földszint",
    shortName: "FSZ",
    kind: "ground",
    order: 0,
    elevationMeters: 0,
    createdAt: now,
  };
}

export function createSurveyLevel(input: { direction: "above" | "below"; levels: SurveyBuildingLevel[]; referenceLevelId: string }): SurveyBuildingLevel {
  const sorted = [...input.levels].sort((left, right) => left.order - right.order);
  const ground = createGroundLevel();
  const bottom = sorted[0] || ground;
  const top = sorted[sorted.length - 1] || ground;
  const now = new Date().toISOString();

  if (input.direction === "below") {
    const basementCount = sorted.filter((level) => level.kind === "basement").length + 1;
    return {
      id: createBuildingModelId("level-basement"),
      name: basementCount === 1 ? "Pince" : `${basementCount}. pinceszint`,
      shortName: basementCount === 1 ? "P" : `P${basementCount}`,
      kind: "basement",
      order: bottom.order - 1,
      elevationMeters: roundSurveyMeasurement(bottom.elevationMeters - 3, 2),
      createdAt: now,
    };
  }

  const floorCount = sorted.filter((level) => level.kind === "floor").length + 1;
  return {
    id: createBuildingModelId("level-floor"),
    name: `${floorCount}. emelet`,
    shortName: `${floorCount}. E`,
    kind: "floor",
    order: top.order + 1,
    elevationMeters: roundSurveyMeasurement(top.elevationMeters + 3, 2),
    createdAt: now,
  };
}

export function getRoomSideLengthMeters(room: SurveyRoom, side: SurveyWallSide) {
  const dimensions = resolveSurveyRoomDimensions(room);
  return side === "top" || side === "bottom" ? dimensions.lengthMeters : dimensions.widthMeters;
}

export function getWallSegmentLengthMeters(room: SurveyRoom, segment: Pick<SurveyWallSegment, "side" | "startRatio" | "endRatio" | "measuredLengthMeters">) {
  const measured = Number(segment.measuredLengthMeters);
  if (Number.isFinite(measured) && measured > 0) return roundSurveyMeasurement(measured, 3);
  return roundSurveyMeasurement(getRoomSideLengthMeters(room, segment.side) * Math.max(0, segment.endRatio - segment.startRatio), 2);
}

export function getWallSegmentHeightMeters(room: SurveyRoom, segment: Pick<SurveyWallSegment, "heightMeters">) {
  const measured = Number(segment.heightMeters);
  if (Number.isFinite(measured) && measured > 0) return roundSurveyMeasurement(measured, 3);
  return roundSurveyMeasurement(Math.max(0, Number(room.height) || 0), 3);
}

export function getRoomSideGeometry(room: SurveyRoom, side: SurveyWallSide): SurveyWallGeometry {
  const lengthMeters = getRoomSideLengthMeters(room, side);
  if (side === "top") return { x1: room.x, y1: room.y, x2: room.x + room.width, y2: room.y, lengthPlanUnits: room.width, lengthMeters };
  if (side === "right") return { x1: room.x + room.width, y1: room.y, x2: room.x + room.width, y2: room.y + room.depth, lengthPlanUnits: room.depth, lengthMeters };
  if (side === "bottom") return { x1: room.x + room.width, y1: room.y + room.depth, x2: room.x, y2: room.y + room.depth, lengthPlanUnits: room.width, lengthMeters };
  return { x1: room.x, y1: room.y + room.depth, x2: room.x, y2: room.y, lengthPlanUnits: room.depth, lengthMeters };
}

export function getWallSegmentGeometry(room: SurveyRoom, segment: Pick<SurveyWallSegment, "side" | "startRatio" | "endRatio" | "measuredLengthMeters" | "planStart" | "planEnd">): SurveyWallGeometry {
  if (segment.planStart && segment.planEnd) {
    const x1 = segment.planStart.x * 900;
    const y1 = segment.planStart.y * 610;
    const x2 = segment.planEnd.x * 900;
    const y2 = segment.planEnd.y * 610;
    return { x1, y1, x2, y2, lengthPlanUnits: Math.hypot(x2 - x1, y2 - y1), lengthMeters: getWallSegmentLengthMeters(room, segment) };
  }
  const sideGeometry = getRoomSideGeometry(room, segment.side);
  const dx = sideGeometry.x2 - sideGeometry.x1;
  const dy = sideGeometry.y2 - sideGeometry.y1;
  const x1 = sideGeometry.x1 + dx * segment.startRatio;
  const y1 = sideGeometry.y1 + dy * segment.startRatio;
  const x2 = sideGeometry.x1 + dx * segment.endRatio;
  const y2 = sideGeometry.y1 + dy * segment.endRatio;
  return {
    x1,
    y1,
    x2,
    y2,
    lengthPlanUnits: sideGeometry.lengthPlanUnits * Math.max(0, segment.endRatio - segment.startRatio),
    lengthMeters: getWallSegmentLengthMeters(room, segment),
  };
}

function rangesOverlap(firstStart: number, firstEnd: number, secondStart: number, secondEnd: number, tolerance = 4) {
  return Math.min(firstEnd, secondEnd) - Math.max(firstStart, secondStart) > tolerance;
}

type SurveyAdjacentWallInterval = {
  startRatio: number;
  endRatio: number;
  adjacentRoomId: string;
  boundaryType: "internal" | "unheated";
};

function lineIntersectsRange(line: number, rangeStart: number, rangeEnd: number, tolerance: number) {
  return rangeStart <= line + tolerance && rangeEnd >= line - tolerance;
}

function getAdjacentWallIntervals(room: SurveyRoom, side: SurveyWallSide, rooms: SurveyRoom[]): SurveyAdjacentWallInterval[] {
  const tolerance = 5;
  const intervals: SurveyAdjacentWallInterval[] = [];
  for (const candidate of rooms) {
    if (candidate.id === room.id) continue;
    let overlapStart = 0;
    let overlapEnd = 0;
    let touching = false;

    if (side === "top") {
      touching = lineIntersectsRange(room.y, candidate.y, candidate.y + candidate.depth, tolerance)
        && rangesOverlap(room.x, room.x + room.width, candidate.x, candidate.x + candidate.width);
      overlapStart = Math.max(room.x, candidate.x);
      overlapEnd = Math.min(room.x + room.width, candidate.x + candidate.width);
      if (touching) intervals.push({
        startRatio: normalizeRatio((overlapStart - room.x) / room.width),
        endRatio: normalizeRatio((overlapEnd - room.x) / room.width),
        adjacentRoomId: candidate.id,
        boundaryType: room.heated !== candidate.heated ? "unheated" : "internal",
      });
      continue;
    }

    if (side === "right") {
      const edge = room.x + room.width;
      touching = lineIntersectsRange(edge, candidate.x, candidate.x + candidate.width, tolerance)
        && rangesOverlap(room.y, room.y + room.depth, candidate.y, candidate.y + candidate.depth);
      overlapStart = Math.max(room.y, candidate.y);
      overlapEnd = Math.min(room.y + room.depth, candidate.y + candidate.depth);
      if (touching) intervals.push({
        startRatio: normalizeRatio((overlapStart - room.y) / room.depth),
        endRatio: normalizeRatio((overlapEnd - room.y) / room.depth),
        adjacentRoomId: candidate.id,
        boundaryType: room.heated !== candidate.heated ? "unheated" : "internal",
      });
      continue;
    }

    if (side === "bottom") {
      const edge = room.y + room.depth;
      touching = lineIntersectsRange(edge, candidate.y, candidate.y + candidate.depth, tolerance)
        && rangesOverlap(room.x, room.x + room.width, candidate.x, candidate.x + candidate.width);
      overlapStart = Math.max(room.x, candidate.x);
      overlapEnd = Math.min(room.x + room.width, candidate.x + candidate.width);
      if (touching) intervals.push({
        startRatio: normalizeRatio((room.x + room.width - overlapEnd) / room.width),
        endRatio: normalizeRatio((room.x + room.width - overlapStart) / room.width),
        adjacentRoomId: candidate.id,
        boundaryType: room.heated !== candidate.heated ? "unheated" : "internal",
      });
      continue;
    }

    touching = lineIntersectsRange(room.x, candidate.x, candidate.x + candidate.width, tolerance)
      && rangesOverlap(room.y, room.y + room.depth, candidate.y, candidate.y + candidate.depth);
    overlapStart = Math.max(room.y, candidate.y);
    overlapEnd = Math.min(room.y + room.depth, candidate.y + candidate.depth);
    if (touching) intervals.push({
      startRatio: normalizeRatio((room.y + room.depth - overlapEnd) / room.depth),
      endRatio: normalizeRatio((room.y + room.depth - overlapStart) / room.depth),
      adjacentRoomId: candidate.id,
      boundaryType: room.heated !== candidate.heated ? "unheated" : "internal",
    });
  }

  return intervals
    .filter((interval) => interval.endRatio - interval.startRatio > 0.001)
    .sort((left, right) => left.startRatio - right.startRatio);
}

export function inferRoomSideBoundary(room: SurveyRoom, side: SurveyWallSide, rooms: SurveyRoom[]) {
  const interval = getAdjacentWallIntervals(room, side, rooms)[0];
  return interval ? { boundaryType: interval.boundaryType, adjacentRoomId: interval.adjacentRoomId } : { boundaryType: "external" as const, adjacentRoomId: undefined };
}

function createWallSegmentsForSide(room: SurveyRoom, side: SurveyWallSide, rooms: SurveyRoom[], externalWallType: string, now: string) {
  const intervals = getAdjacentWallIntervals(room, side, rooms);
  const boundaries = [...new Set([0, 1, ...intervals.flatMap((interval) => [interval.startRatio, interval.endRatio])])].sort((left, right) => left - right);
  const raw = boundaries.slice(0, -1).map((startRatio, index) => {
    const endRatio = boundaries[index + 1];
    const midpoint = (startRatio + endRatio) / 2;
    const adjacent = intervals.find((interval) => midpoint > interval.startRatio - 0.0001 && midpoint < interval.endRatio + 0.0001);
    return {
      startRatio,
      endRatio,
      boundaryType: adjacent ? adjacent.boundaryType : "external" as const,
      adjacentRoomId: adjacent?.adjacentRoomId,
    };
  }).filter((segment) => segment.endRatio - segment.startRatio > 0.001);

  const merged: typeof raw = [];
  for (const segment of raw) {
    const previous = merged[merged.length - 1];
    if (previous && previous.boundaryType === segment.boundaryType && previous.adjacentRoomId === segment.adjacentRoomId) previous.endRatio = segment.endRatio;
    else merged.push({ ...segment });
  }

  return merged.map((segment, index): SurveyWallSegment => ({
    id: `wall-${room.id}-${side}-${index}`,
    levelId: room.levelId || "level-ground",
    roomId: room.id,
    side,
    startRatio: roundSurveyMeasurement(segment.startRatio, 4),
    endRatio: roundSurveyMeasurement(segment.endRatio, 4),
    boundaryType: segment.boundaryType,
    wallType: segment.boundaryType === "external"
      ? (externalWallType || "Külső fal – ellenőrizendő")
      : segment.boundaryType === "unheated"
        ? "Fűtetlen tér felőli határoló fal"
        : "Belső válaszfal",
    thicknessCm: segment.boundaryType === "external" ? 38 : segment.boundaryType === "unheated" ? 25 : 10,
    adjacentRoomId: segment.adjacentRoomId,
    note: "",
    isAutoGenerated: true,
    createdAt: now,
    updatedAt: now,
  }));
}

export function createDefaultWallSegmentsForRoom(room: SurveyRoom, rooms: SurveyRoom[], externalWallType = "Külső fal – ellenőrizendő"): SurveyWallSegment[] {
  const now = new Date().toISOString();
  return (["top", "right", "bottom", "left"] as SurveyWallSide[]).flatMap((side) => createWallSegmentsForSide(room, side, rooms, externalWallType, now));
}

export function ensureWallSegmentsForRooms(rooms: SurveyRoom[], segments: SurveyWallSegment[] | undefined, externalWallType = "") {
  const current = Array.isArray(segments) ? [...segments] : [];
  for (const room of rooms) {
    const roomSegments = current.filter((segment) => segment.roomId === room.id);
    if (!roomSegments.length) current.push(...createDefaultWallSegmentsForRoom(room, rooms.filter((item) => (item.levelId || "level-ground") === (room.levelId || "level-ground")), externalWallType));
  }
  return current.filter((segment) => rooms.some((room) => room.id === segment.roomId));
}

export function rebuildAutomaticWallSegmentsForRooms(rooms: SurveyRoom[], segments: SurveyWallSegment[], externalWallType = "") {
  const roomIds = new Set(rooms.map((room) => room.id));
  const outsideLevel = segments.filter((segment) => !roomIds.has(segment.roomId));
  const manualSegments = segments.filter((segment) => roomIds.has(segment.roomId) && segment.isAutoGenerated === false);
  const rebuilt = [...outsideLevel, ...manualSegments];

  for (const room of rooms) {
    const manualSides = new Set(manualSegments.filter((segment) => segment.roomId === room.id).map((segment) => segment.side));
    const automatic = createDefaultWallSegmentsForRoom(room, rooms, externalWallType).filter((segment) => !manualSides.has(segment.side));
    rebuilt.push(...automatic);
  }
  return rebuilt;
}


export type SurveyDynamicWallReconcileResult = {
  wallSegments: SurveyWallSegment[];
  wallOpenings: SurveyWallOpening[];
};

function intervalOverlap(startA: number, endA: number, startB: number, endB: number) {
  return Math.max(0, Math.min(endA, endB) - Math.max(startA, startB));
}

function uniqueRatios(values: number[]) {
  return [...new Set(values.map((value) => roundSurveyMeasurement(normalizeRatio(value), 4)))].sort((left, right) => left - right);
}

function findBestExistingSegment(
  target: Pick<SurveyWallSegment, "startRatio" | "endRatio" | "boundaryType" | "adjacentRoomId">,
  existing: SurveyWallSegment[],
  usedIds: Set<string>,
) {
  let best: SurveyWallSegment | null = null;
  let bestScore = -1;
  for (const segment of existing) {
    if (usedIds.has(segment.id)) continue;
    const overlap = intervalOverlap(target.startRatio, target.endRatio, segment.startRatio, segment.endRatio);
    const sameBoundary = target.boundaryType === segment.boundaryType;
    const sameAdjacent = (target.adjacentRoomId || "") === (segment.adjacentRoomId || "");
    const midpointTarget = (target.startRatio + target.endRatio) / 2;
    const midpointExisting = (segment.startRatio + segment.endRatio) / 2;
    const distancePenalty = Math.abs(midpointTarget - midpointExisting);
    const score = overlap * 100 + (sameBoundary ? 20 : 0) + (sameAdjacent ? 8 : 0) + (segment.isAutoGenerated === false ? 3 : 0) - distancePenalty;
    if (score > bestScore) {
      best = segment;
      bestScore = score;
    }
  }
  return bestScore > 0.001 ? best : null;
}

/**
 * A helyiségek aktuális geometriája alapján újraépíti az automatikus belső/külső
 * falszakaszokat, miközben a kézi szakaszhatárokat, rétegrendeket, vastagságokat
 * és a falra helyezett nyílászárókat a lehető legnagyobb átfedés alapján megőrzi.
 */
export function reconcileDynamicWallModelForRooms(
  rooms: SurveyRoom[],
  segments: SurveyWallSegment[],
  openings: SurveyWallOpening[],
  externalWallType = "Külső fal – ellenőrizendő",
): SurveyDynamicWallReconcileResult {
  const roomIds = new Set(rooms.map((room) => room.id));
  const outsideSegments = segments.filter((segment) => !roomIds.has(segment.roomId));
  const planTransferredSegments = segments.filter((segment) => roomIds.has(segment.roomId) && Boolean(segment.planWallSuggestionId));
  const existingLevelSegments = segments.filter((segment) => roomIds.has(segment.roomId) && !segment.planWallSuggestionId);
  const oldSegmentById = new Map(existingLevelSegments.map((segment) => [segment.id, segment]));
  const nextLevelSegments: SurveyWallSegment[] = [];
  const now = new Date().toISOString();

  for (const room of rooms) {
    for (const side of ["top", "right", "bottom", "left"] as SurveyWallSide[]) {
      const existingSide = existingLevelSegments
        .filter((segment) => segment.roomId === room.id && segment.side === side)
        .sort((left, right) => left.startRatio - right.startRatio);
      const inferredSide = createWallSegmentsForSide(room, side, rooms, externalWallType, now);
      const manualBoundaries = existingSide
        .filter((segment) => segment.isAutoGenerated === false)
        .flatMap((segment) => [segment.startRatio, segment.endRatio]);
      const boundaries = uniqueRatios([0, 1, ...inferredSide.flatMap((segment) => [segment.startRatio, segment.endRatio]), ...manualBoundaries]);
      const usedExistingIds = new Set<string>();

      for (let index = 0; index < boundaries.length - 1; index += 1) {
        const startRatio = boundaries[index];
        const endRatio = boundaries[index + 1];
        if (endRatio - startRatio <= 0.001) continue;
        const midpoint = (startRatio + endRatio) / 2;
        const inferred = inferredSide.find((segment) => midpoint >= segment.startRatio - 0.0001 && midpoint <= segment.endRatio + 0.0001)
          || inferredSide[0];
        if (!inferred) continue;

        const target = {
          startRatio,
          endRatio,
          boundaryType: inferred.boundaryType,
          adjacentRoomId: inferred.adjacentRoomId,
        };
        const source = findBestExistingSegment(target, existingSide, usedExistingIds);
        if (source) usedExistingIds.add(source.id);
        const boundaryUnchanged = source?.boundaryType === target.boundaryType;
        const preserveManualMaterial = source?.isAutoGenerated === false;
        const defaultWallType = target.boundaryType === "external"
          ? (externalWallType || "Külső fal – ellenőrizendő")
          : target.boundaryType === "unheated"
            ? "Fűtetlen tér felőli határoló fal"
            : "Belső válaszfal";
        const defaultThickness = target.boundaryType === "external" ? 38 : target.boundaryType === "unheated" ? 25 : 10;

        nextLevelSegments.push({
          id: source?.id || createBuildingModelId(`wall-${room.id}-${side}`),
          levelId: room.levelId || "level-ground",
          roomId: room.id,
          side,
          startRatio,
          endRatio,
          boundaryType: target.boundaryType,
          wallType: source && (boundaryUnchanged || preserveManualMaterial) ? source.wallType : defaultWallType,
          thicknessCm: source && (boundaryUnchanged || preserveManualMaterial) ? source.thicknessCm : defaultThickness,
          assemblyId: source?.assemblyId,
          adjacentRoomId: target.adjacentRoomId,
          note: source?.note || "",
          isAutoGenerated: source?.isAutoGenerated === false ? false : true,
          createdAt: source?.createdAt || now,
          updatedAt: now,
        });
      }
    }
  }

  const nextOpenings = openings.map((opening) => {
    const oldSegment = oldSegmentById.get(opening.wallSegmentId);
    if (!oldSegment || !roomIds.has(oldSegment.roomId)) return opening;
    const globalRatio = oldSegment.startRatio + opening.offsetRatio * Math.max(0.0001, oldSegment.endRatio - oldSegment.startRatio);
    const candidates = nextLevelSegments.filter((segment) => segment.roomId === oldSegment.roomId && segment.side === oldSegment.side);
    const target = candidates.find((segment) => globalRatio >= segment.startRatio - 0.0001 && globalRatio <= segment.endRatio + 0.0001)
      || candidates.sort((left, right) => Math.abs((left.startRatio + left.endRatio) / 2 - globalRatio) - Math.abs((right.startRatio + right.endRatio) / 2 - globalRatio))[0];
    if (!target) return opening;
    return {
      ...opening,
      levelId: target.levelId,
      roomId: target.roomId,
      wallSegmentId: target.id,
      offsetRatio: Math.min(1, Math.max(0, (globalRatio - target.startRatio) / Math.max(0.0001, target.endRatio - target.startRatio))),
      updatedAt: now,
    };
  });

  return {
    wallSegments: [...outsideSegments, ...nextLevelSegments, ...planTransferredSegments],
    wallOpenings: nextOpenings,
  };
}

export type SurveyExternalWallLengthSummary = {
  totalMeters: number;
  byDirection: Record<string, number>;
  segmentCount: number;
};

export function calculateExternalWallLengthSummary(
  rooms: SurveyRoom[],
  segments: SurveyWallSegment[],
  northAngle: number,
): SurveyExternalWallLengthSummary {
  const roomById = new Map(rooms.map((room) => [room.id, room]));
  const byDirection: Record<string, number> = {};
  let totalMeters = 0;
  let segmentCount = 0;
  for (const segment of segments) {
    if (segment.boundaryType !== "external") continue;
    const room = roomById.get(segment.roomId);
    if (!room) continue;
    const length = getWallSegmentLengthMeters(room, segment);
    const direction = getWallSegmentOrientationLabel(segment, northAngle).label;
    totalMeters += length;
    byDirection[direction] = roundSurveyMeasurement((byDirection[direction] || 0) + length, 2);
    segmentCount += 1;
  }
  return { totalMeters: roundSurveyMeasurement(totalMeters, 2), byDirection, segmentCount };
}

export function splitWallSegment(segment: SurveyWallSegment) {
  const midpoint = roundSurveyMeasurement((segment.startRatio + segment.endRatio) / 2, 4);
  const now = new Date().toISOString();
  return [
    { ...segment, endRatio: midpoint, isAutoGenerated: false, updatedAt: now },
    { ...segment, id: createBuildingModelId("wall-segment"), startRatio: midpoint, isAutoGenerated: false, updatedAt: now, createdAt: now },
  ];
}

export function getWallSideBaseAzimuth(side: SurveyWallSide, northAngle: number) {
  const topAzimuth = ((-northAngle % 360) + 360) % 360;
  const offsets: Record<SurveyWallSide, number> = { top: 0, right: 90, bottom: 180, left: 270 };
  return (topAzimuth + offsets[side]) % 360;
}

export function getCompassLabelFromAzimuth(azimuth: number) {
  const directions = ["É", "ÉK", "K", "DK", "D", "DNy", "Ny", "ÉNy"];
  return directions[Math.round((((azimuth % 360) + 360) % 360) / 45) % 8];
}

export function getWallSegmentOrientationLabel(segment: Pick<SurveyWallSegment, "side" | "orientationDegrees">, northAngle: number) {
  const measured = Number(segment.orientationDegrees);
  if (Number.isFinite(measured)) {
    const azimuth = ((measured % 360) + 360) % 360;
    return { azimuth, label: getCompassLabelFromAzimuth(azimuth) };
  }
  return getWallOrientationLabel(segment.side, northAngle);
}

export function getWallOrientationLabel(side: SurveyWallSide, northAngle: number) {
  const azimuth = getWallSideBaseAzimuth(side, northAngle);
  return { azimuth, label: getCompassLabelFromAzimuth(azimuth) };
}

export function getPaperDimensionsMm(settings: SurveyPlanSheetSettings) {
  const base = surveyPaperSizesMm[settings.paperSize];
  return settings.orientation === "landscape" ? { width: base.height, height: base.width } : { width: base.width, height: base.height };
}

export function getRecommendedSurveyScale(rooms: SurveyRoom[], settings: SurveyPlanSheetSettings) {
  if (!rooms.length) return 50;
  const minX = Math.min(...rooms.map((room) => room.x));
  const minY = Math.min(...rooms.map((room) => room.y));
  const maxX = Math.max(...rooms.map((room) => room.x + room.width));
  const maxY = Math.max(...rooms.map((room) => room.y + room.depth));
  const widthMeters = (maxX - minX) / 60;
  const heightMeters = (maxY - minY) / 60;
  const paper = getPaperDimensionsMm(settings);
  const printableWidthMm = Math.max(50, paper.width - 30);
  const printableHeightMm = Math.max(50, paper.height - 30);
  const required = Math.max((widthMeters * 1000) / printableWidthMm, (heightMeters * 1000) / printableHeightMm);
  return surveyScaleOptions.find((scale) => scale >= required) || surveyScaleOptions[surveyScaleOptions.length - 1];
}

export function createDefaultPlanSheet(): SurveyPlanSheetSettings {
  return { paperSize: "A3", orientation: "landscape", scaleMode: "auto", scaleDenominator: 50 };
}

export function normalizeRatio(value: number) {
  return Math.min(1, Math.max(0, value));
}

export type SurveyRoomOverlap = {
  roomAId: string;
  roomBId: string;
  overlapWidthPlanUnits: number;
  overlapHeightPlanUnits: number;
  overlapAreaSquareMeters: number;
};

export function detectSurveyRoomOverlaps(rooms: SurveyRoom[]): SurveyRoomOverlap[] {
  const overlaps: SurveyRoomOverlap[] = [];
  for (let leftIndex = 0; leftIndex < rooms.length; leftIndex += 1) {
    for (let rightIndex = leftIndex + 1; rightIndex < rooms.length; rightIndex += 1) {
      const left = rooms[leftIndex];
      const right = rooms[rightIndex];
      const overlapWidth = Math.max(0, Math.min(left.x + left.width, right.x + right.width) - Math.max(left.x, right.x));
      const overlapHeight = Math.max(0, Math.min(left.y + left.depth, right.y + right.depth) - Math.max(left.y, right.y));
      if (overlapWidth <= 1 || overlapHeight <= 1) continue;
      overlaps.push({
        roomAId: left.id,
        roomBId: right.id,
        overlapWidthPlanUnits: roundSurveyMeasurement(overlapWidth, 2),
        overlapHeightPlanUnits: roundSurveyMeasurement(overlapHeight, 2),
        overlapAreaSquareMeters: roundSurveyMeasurement((overlapWidth / 60) * (overlapHeight / 60), 2),
      });
    }
  }
  return overlaps;
}
