"use strict";

const EXECUTION_REQUEST_START = "BENJADMIN_EXECUTION_REQUEST_V1";
const EXECUTION_REQUEST_END = "BENJADMIN_EXECUTION_REQUEST_END";
const EXECUTION_RESULT_START = "BENJADMIN_EXECUTION_RESULT_V1";
const EXECUTION_RESULT_END = "BENJADMIN_EXECUTION_RESULT_END";
const ACTIONS = new Set(["LIST_FILES","READ_FILE","SEARCH_FILES","WRITE_FILE","GIT_STATUS","GIT_DIFF","GIT_DIFF_CHECK","RUN_DEV_COMMAND"]);
const WORKERS = new Set(["ARMINAI","OUTMINAI","BENJAMINAI","BENAI","JAZMINAI"]);
const COMMANDS = new Set(["TSC","LINT","CONTRACT"]);
function text(value,max=200000){return String(value??"").trim().slice(0,max)}
function record(value){return value&&typeof value==="object"&&!Array.isArray(value)?value:{}}
function parseDeveloperGridExecutionRequest(raw){
  const body=String(raw||"");const start=body.lastIndexOf(EXECUTION_REQUEST_START);if(start<0)return{ok:false,code:"EXECUTION_REQUEST_MARKER_MISSING",error:"A BENJADMIN_EXECUTION_REQUEST_V1 marker hiányzik."};const jsonStart=start+EXECUTION_REQUEST_START.length;const end=body.indexOf(EXECUTION_REQUEST_END,jsonStart);if(end<0)return{ok:false,code:"EXECUTION_REQUEST_END_MISSING",error:"A BENJADMIN_EXECUTION_REQUEST_END marker hiányzik."};let parsed;try{parsed=JSON.parse(body.slice(jsonStart,end).trim())}catch{return{ok:false,code:"EXECUTION_REQUEST_JSON_INVALID",error:"Az execution request JSON nem érvényes."}}
  const row=record(parsed);const schemaVersion=Number(row.schemaVersion);const requestId=text(row.requestId,120);const taskId=text(row.taskId,220);const sessionId=text(row.sessionId,240);const workerRaw=text(row.workerCode,40).toUpperCase();const workerCode=workerRaw==="BENAI"?"BENJAMINAI":workerRaw;const sourceProofSha256=text(row.sourceProofSha256,80).toLowerCase();const action=text(row.action,40).toUpperCase();
  if(schemaVersion!==1)return{ok:false,code:"EXECUTION_REQUEST_SCHEMA_INVALID",error:"Ismeretlen execution schemaVersion."};if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{2,119}$/.test(requestId))return{ok:false,code:"EXECUTION_REQUEST_ID_INVALID",error:"Érvénytelen execution requestId."};if(!taskId||!sessionId||!WORKERS.has(workerRaw)||!/^[0-9a-f]{64}$/.test(sourceProofSha256))return{ok:false,code:"EXECUTION_REQUEST_IDENTITY_INVALID",error:"Hiányos execution identity."};if(!ACTIONS.has(action))return{ok:false,code:"EXECUTION_REQUEST_ACTION_INVALID",error:"Ismeretlen execution action."};
  const path=text(row.path,1000);const query=text(row.query,500);const content=typeof row.content==="string"?row.content:"";const command=text(row.command,80).toUpperCase();if(["READ_FILE","WRITE_FILE"].includes(action)&&!path)return{ok:false,code:"EXECUTION_REQUEST_PATH_REQUIRED",error:`${action} path kötelező.`};if(action==="SEARCH_FILES"&&!query)return{ok:false,code:"EXECUTION_REQUEST_QUERY_REQUIRED",error:"SEARCH_FILES query kötelező."};if(action==="RUN_DEV_COMMAND"&&!COMMANDS.has(command))return{ok:false,code:"EXECUTION_REQUEST_COMMAND_INVALID",error:"RUN_DEV_COMMAND csak TSC, LINT vagy CONTRACT lehet."};if(action==="RUN_DEV_COMMAND"&&command==="CONTRACT"&&!path)return{ok:false,code:"EXECUTION_REQUEST_CONTRACT_PATH_REQUIRED",error:"CONTRACT futtatáshoz path kötelező."};if(Buffer.byteLength(content,"utf8")>384*1024)return{ok:false,code:"EXECUTION_REQUEST_CONTENT_TOO_LARGE",error:"A WRITE_FILE tartalom túl nagy."};
  return{ok:true,request:{schemaVersion:1,requestId,taskId,sessionId,workerCode,sourceProofSha256,action,...(path?{path}:{}),...(query?{query}:{}),...(action==="WRITE_FILE"?{content}:{}),...(Number.isInteger(Number(row.startLine))?{startLine:Number(row.startLine)}:{}),...(Number.isInteger(Number(row.endLine))?{endLine:Number(row.endLine)}:{}),...(Number.isInteger(Number(row.depth))?{depth:Number(row.depth)}:{}),...(command?{command}:{})}};
}
function buildDeveloperGridExecutionResultPrompt(payload){
  const safe=record(payload);const execution=record(safe.execution);const json=JSON.stringify({schemaVersion:1,requestId:text(safe.requestId,120),taskId:text(safe.taskId,220),sessionId:text(safe.sessionId,240),action:text(safe.action,40).toUpperCase(),status:text(execution.status,40).toUpperCase()||"FAIL",code:text(execution.code,120),summary:text(execution.summary,1200),data:record(execution.data),replayed:safe.replayed===true,productionAccess:"DENY"},null,2);
  return ["BENJADMIN_PROMPT_KIND: EXECUTION_RESULT_V1",EXECUTION_RESULT_START,json,EXECUTION_RESULT_END,"A Central Core Execution Bridge eredménye fent látható. Folytasd ugyanazt a taskot. Ha a data.authoritativeSourceProofSha256 mező jelen van, a következő execution request sourceProofSha256 mezőjében ezt használd. Ha további fájlművelet kell, adj ki új, egyedi requestId-jú BENJADMIN_EXECUTION_REQUEST_V1 blokkot. PROD/deploy/restart/migration továbbra is tiltott."].join("\n");
}
module.exports={EXECUTION_REQUEST_START,EXECUTION_REQUEST_END,EXECUTION_RESULT_START,EXECUTION_RESULT_END,parseDeveloperGridExecutionRequest,buildDeveloperGridExecutionResultPrompt};
