export type CostWorkType = "new_build" | "renovation" | "repair" | "operation";
export type CostDiscipline =
  | "demolition_preparation"
  | "masonry_drywall"
  | "concrete_foundation"
  | "roof"
  | "insulation"
  | "openings"
  | "tiling"
  | "painting"
  | "electrical"
  | "mechanical"
  | "renewable_energy"
  | "external_works"
  | "other";

export type CostQuantityBase =
  | "floorArea"
  | "roomCount"
  | "facadeArea"
  | "roofArea"
  | "manual"
  | "package"
  | "piece";

export type CostDetailLine = {
  id: string;
  name: string;
  unit: string;
  defaultEnabled: boolean;
  quantityBase: CostQuantityBase;
  quantityMultiplier: number;
  minQuantity?: number;
  userVisibleHint: boolean;
  adminDetailedOnly: boolean;
  note?: string;
};

export type CostMajorItem = {
  id: string;
  name: string;
  discipline: CostDiscipline;
  workTypes: CostWorkType[];
  group: string;
  unit: string;
  description: string;
  relatedWorks: string[];
  quantityBase: CostQuantityBase;
  quantityMultiplier: number;
  minQuantity: number;
  materialUnitPrice: number;
  laborUnitPrice: number;
  otherCost: number;
  defaultEnabled: boolean;
  source: "dimpro_demo" | "engy_reference_later" | "private_later";
  confidence: "demo" | "low" | "medium" | "high";
  detailLines: CostDetailLine[];
};

export const disciplineLabels: Record<CostDiscipline, string> = {
  demolition_preparation: "Előkészítés, bontás",
  masonry_drywall: "Falazás, szárazépítés",
  concrete_foundation: "Alapozás, beton, vasbeton",
  roof: "Tető, ács, bádogos",
  insulation: "Hő- és vízszigetelés",
  openings: "Nyílászárók, árnyékolás",
  tiling: "Burkolás",
  painting: "Festés, felületképzés",
  electrical: "Villanyszerelés",
  mechanical: "Épületgépészet, komfort",
  renewable_energy: "Energetikai / megújuló rendszerek",
  external_works: "Külső munkák, kert, udvar",
  other: "Egyéb járulékos költségek",
};

const floorTilingDetails: CostDetailLine[] = [
  { id: "floor-cleaning", name: "Felület portalanítása", unit: "m²", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: false },
  { id: "floor-primer", name: "Mélyalapozás", unit: "m²", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: false },
  { id: "floor-leveling", name: "Aljzatkiegyenlítés", unit: "m²", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 0.5, userVisibleHint: true, adminDetailedOnly: false, note: "Felújításnál opcionális, szükség esetén teljes felületre is állítható." },
  { id: "floor-tiling-laying", name: "Padlóburkolás ragasztással", unit: "m²", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: false },
  { id: "floor-grouting", name: "Fugázás", unit: "m²", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: false },
  { id: "skirting-tiling", name: "Lábazat burkolás", unit: "fm", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 0.65, userVisibleHint: true, adminDetailedOnly: false },
  { id: "silicone-sealing", name: "Szilikonozás", unit: "fm", defaultEnabled: true, quantityBase: "floorArea", quantityMultiplier: 0.25, userVisibleHint: true, adminDetailedOnly: false },
  { id: "tile-edge-profile", name: "Élvédő / lezáró profil", unit: "fm", defaultEnabled: false, quantityBase: "manual", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: false },
  { id: "old-tile-demolition", name: "Régi burkolat bontása", unit: "m²", defaultEnabled: false, quantityBase: "floorArea", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: false },
  { id: "adhesive-removal", name: "Régi ragasztó eltávolítása", unit: "m²", defaultEnabled: false, quantityBase: "floorArea", quantityMultiplier: 1, userVisibleHint: true, adminDetailedOnly: true },
];

function details(names: string[]): CostDetailLine[] {
  return names.map((name, index) => ({
    id: name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `detail-${index}`,
    name,
    unit: index < 3 ? "m²" : "db",
    defaultEnabled: index < 5,
    quantityBase: index < 3 ? "floorArea" : "manual",
    quantityMultiplier: index < 3 ? 1 : 1,
    userVisibleHint: true,
    adminDetailedOnly: index > 6,
  }));
}

export const costMajorItems: CostMajorItem[] = [
  {
    id: "demolition",
    name: "Bontási munkák",
    discipline: "demolition_preparation",
    workTypes: ["renovation", "repair"],
    group: "Bontás",
    unit: "m²",
    description: "Felújítási bontások egyszerűsített becslési tétele.",
    relatedWorks: ["burkolatbontás", "válaszfal bontás", "szerelvények bontása", "porvédelem", "sitt mozgatás"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.35,
    minQuantity: 1,
    materialUnitPrice: 450,
    laborUnitPrice: 6200,
    otherCost: 85000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Terület előkészítés", "Bontási munka", "Törmelék összegyűjtés", "Anyagmozgatás", "Porvédelem", "Ideiglenes takarás", "Kézi bontás nehezen hozzáférhető helyen"]),
  },
  {
    id: "waste",
    name: "Sittszállítás és hulladékkezelés",
    discipline: "demolition_preparation",
    workTypes: ["renovation", "repair"],
    group: "Bontás",
    unit: "konténer",
    description: "Konténeres vagy zsákos hulladékelszállítás becslése.",
    relatedWorks: ["konténer rendelés", "rakodás", "deponálás", "szállítás", "lerakási díj"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.08,
    minQuantity: 1,
    materialUnitPrice: 0,
    laborUnitPrice: 0,
    otherCost: 180000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Konténer rendelés", "Sitt zsákolás", "Rakodás", "Szállítás", "Lerakási díj", "Többlet forduló"]),
  },
  {
    id: "floor_tiling",
    name: "Padlóburkolás",
    discipline: "tiling",
    workTypes: ["new_build", "renovation", "repair"],
    group: "Burkolás",
    unit: "m²",
    description: "Hidegburkolat készítése padlón, egyszerűsített gyorskalkulátor tételként.",
    relatedWorks: ["felület portalanítás", "mélyalapozás", "aljzatkiegyenlítés", "padlóburkolás", "fugázás", "lábazat", "szilikonozás"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.55,
    minQuantity: 8,
    materialUnitPrice: 11500,
    laborUnitPrice: 9800,
    otherCost: 120000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: floorTilingDetails,
  },
  {
    id: "wall_tiling",
    name: "Falburkolás",
    discipline: "tiling",
    workTypes: ["new_build", "renovation", "repair"],
    group: "Burkolás",
    unit: "m²",
    description: "Fürdő, WC, konyha vagy egyéb falburkolat egyszerűsített becslése.",
    relatedWorks: ["felület előkészítés", "mélyalapozás", "falburkolás", "fugázás", "élvédő", "szilikonozás"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.45,
    minQuantity: 6,
    materialUnitPrice: 9800,
    laborUnitPrice: 10500,
    otherCost: 90000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Felület előkészítés", "Mélyalapozás", "Falburkolás ragasztással", "Fugázás", "Élvédő elhelyezés", "Szilikonozás", "Régi csempe bontása"]),
  },
  {
    id: "painting",
    name: "Festés, glettelés",
    discipline: "painting",
    workTypes: ["new_build", "renovation", "repair"],
    group: "Festés",
    unit: "m²",
    description: "Belső festési munkák becslése fal- és mennyezetfelületekre.",
    relatedWorks: ["takarás", "javítás", "glettelés", "csiszolás", "mélyalapozás", "festés 2 rétegben", "takarítás"],
    quantityBase: "floorArea",
    quantityMultiplier: 2.7,
    minQuantity: 30,
    materialUnitPrice: 1900,
    laborUnitPrice: 3100,
    otherCost: 35000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Takarás", "Falhibák javítása", "Glettelés", "Csiszolás", "Mélyalapozás", "Diszperziós festés 2 rétegben", "Takarítás"]),
  },
  {
    id: "electric_rewire",
    name: "Villanyszerelés / vezetékcsere",
    discipline: "electrical",
    workTypes: ["renovation", "repair", "new_build"],
    group: "Villanyszerelés",
    unit: "m²",
    description: "Lakóépület villamos hálózatának korszerűsítése, alumínium vezeték cseréje rézvezetékre.",
    relatedWorks: ["horonyvésés", "védőcsövezés", "rézvezeték behúzás", "dobozolás", "dugaljak", "kapcsolók", "elosztó csere", "FI-relé"],
    quantityBase: "floorArea",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 7200,
    laborUnitPrice: 6200,
    otherCost: 180000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Horonyvésés", "Védőcsövezés", "Rézvezeték behúzás", "Kötődobozok", "Szerelvénydobozok", "Dugaljak és kapcsolók", "Elosztó csere", "FI-relé beépítés", "Mérés / jegyzőkönyv", "Helyreállítási munkák"]),
  },
  {
    id: "mechanical",
    name: "Gépészeti korszerűsítés",
    discipline: "mechanical",
    workTypes: ["renovation", "repair", "new_build"],
    group: "Gépészet",
    unit: "m²",
    description: "Víz, szennyvíz, fűtési és HMV jellegű gépészeti munkák becslése.",
    relatedWorks: ["vízvezeték csere", "szennyvíz csere", "kiállások", "szerelvényezés", "nyomáspróba", "fűtési átalakítás"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.22,
    minQuantity: 1,
    materialUnitPrice: 26000,
    laborUnitPrice: 21000,
    otherCost: 240000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Bontás és lezárás", "Vízvezeték csere", "Szennyvízvezeték csere", "Gépészeti kiállások", "Szaniter szerelvényezés", "Nyomáspróba", "Fűtési átalakítás", "Helyreállítás"]),
  },
  {
    id: "bathroom",
    name: "Fürdőszoba teljes felújítás",
    discipline: "mechanical",
    workTypes: ["renovation", "repair"],
    group: "Fürdőszoba",
    unit: "db",
    description: "Fürdőszoba komplex felújításának egyszerűsített tételcsomagja.",
    relatedWorks: ["bontás", "vízszigetelés", "gépészeti kiállások", "villanyszerelés", "falburkolás", "padlóburkolás", "szaniterek", "szilikonozás"],
    quantityBase: "piece",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 950000,
    laborUnitPrice: 820000,
    otherCost: 180000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Bontás", "Sittszállítás", "Vízvezeték kiállások", "Csatorna kiállások", "Villanyszerelés", "Vízszigetelés", "Aljzatkiegyenlítés", "Falburkolás", "Padlóburkolás", "Szaniterek elhelyezése", "Szilikonozás", "Szerelvényezés"]),
  },
  {
    id: "kitchen",
    name: "Konyha előkészítés / felújítás",
    discipline: "mechanical",
    workTypes: ["renovation", "new_build"],
    group: "Konyha",
    unit: "db",
    description: "Konyhai gépészeti és villamos előkészítés becslése.",
    relatedWorks: ["víz kiállás", "szennyvíz kiállás", "elektromos kiállások", "burkolás", "hátfal", "elszívó előkészítés"],
    quantityBase: "piece",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 1050000,
    laborUnitPrice: 560000,
    otherCost: 170000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Víz kiállás", "Szennyvíz kiállás", "Elektromos kiállások", "Főzőlap / sütő kiállás", "Hátfal burkolás", "Elszívó előkészítés", "Bútorozás előkészítő munkák"]),
  },
  {
    id: "windows",
    name: "Nyílászárócsere",
    discipline: "openings",
    workTypes: ["renovation", "repair", "new_build"],
    group: "Nyílászáró",
    unit: "db",
    description: "Külső vagy belső nyílászárók cseréjének egyszerűsített becslése.",
    relatedWorks: ["bontás", "beépítés", "purhab", "párkány", "takaróléc", "kávajavítás", "redőny előkészítés"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.055,
    minQuantity: 3,
    materialUnitPrice: 185000,
    laborUnitPrice: 52000,
    otherCost: 90000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Régi nyílászáró bontása", "Új nyílászáró beépítése", "Purhabozás", "Külső-belső takarás", "Párkány elhelyezés", "Kávajavítás", "Redőny / árnyékoló előkészítés"]),
  },
  {
    id: "insulation_facade",
    name: "Homlokzati hőszigetelés",
    discipline: "insulation",
    workTypes: ["renovation", "new_build"],
    group: "Hőszigetelés",
    unit: "m²",
    description: "Homlokzati hőszigetelő rendszer egyszerűsített becslése.",
    relatedWorks: ["állványozás", "felület előkészítés", "indítósín", "ragasztás", "hőszigetelő lap", "dübelezés", "hálózás", "alapozás", "vékonyvakolat"],
    quantityBase: "floorArea",
    quantityMultiplier: 1.35,
    minQuantity: 40,
    materialUnitPrice: 9800,
    laborUnitPrice: 11500,
    otherCost: 260000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Állványozás", "Felület előkészítés", "Indítósín", "Ragasztás", "Hőszigetelő lap elhelyezés", "Dübelezés", "Hálózás", "Alapozás", "Vékonyvakolat", "Lábazati kialakítás", "Párkányok / csatlakozások"]),
  },
  {
    id: "insulation_attic",
    name: "Padlásfödém / tetőtéri hőszigetelés",
    discipline: "insulation",
    workTypes: ["renovation", "new_build"],
    group: "Hőszigetelés",
    unit: "m²",
    description: "Padlásfödém vagy tetőtéri hőszigetelés családi házas munkákhoz.",
    relatedWorks: ["fólia", "hőszigetelés", "párazárás", "járófelület", "csatlakozások"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.85,
    minQuantity: 30,
    materialUnitPrice: 7600,
    laborUnitPrice: 5600,
    otherCost: 90000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Felület előkészítés", "Párazáró / fólia réteg", "Hőszigetelés elhelyezése", "Járófelület kialakítás", "Csatlakozások lezárása"]),
  },
  {
    id: "roof",
    name: "Tetőfelújítás",
    discipline: "roof",
    workTypes: ["renovation", "repair", "new_build"],
    group: "Tető",
    unit: "m²",
    description: "Tetőhéjazat, léc, fólia és kapcsolódó ács/bádogos munkák egyszerűsített becslése.",
    relatedWorks: ["héjazat bontás", "fólia", "ellenléc", "tetőléc", "héjazat", "bádogos elemek", "ereszcsatorna"],
    quantityBase: "floorArea",
    quantityMultiplier: 0.85,
    minQuantity: 45,
    materialUnitPrice: 17500,
    laborUnitPrice: 16800,
    otherCost: 420000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Régi héjazat bontása", "Fóliázás", "Ellenlécezés", "Tetőlécezés", "Új héjazat elhelyezés", "Bádogos elemek", "Ereszcsatorna csere", "Kémény körüli javítás"]),
  },
  {
    id: "fence_build",
    name: "Kerítés építés",
    discipline: "external_works",
    workTypes: ["new_build", "renovation", "repair"],
    group: "Külső munkák",
    unit: "fm",
    description: "Családi házas kerítés építés vagy csere egyszerűsített tétele.",
    relatedWorks: ["kitűzés", "földmunka", "oszlopalap", "zsalukő / lábazat", "oszlop", "mezőelem", "kapu előkészítés"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 10,
    materialUnitPrice: 28000,
    laborUnitPrice: 18000,
    otherCost: 160000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Kitűzés", "Földmunka", "Oszlopalap készítés", "Kerítés lábazat", "Oszlopok elhelyezése", "Mezőelemek szerelése", "Kapu előkészítés", "Felületvédelem"]),
  },
  {
    id: "driveway",
    name: "Bejáró / térburkolat készítés",
    discipline: "external_works",
    workTypes: ["new_build", "renovation", "repair"],
    group: "Külső munkák",
    unit: "m²",
    description: "Autóbejáró, járda vagy udvari térburkolat egyszerűsített becslése.",
    relatedWorks: ["tükörkiemelés", "ágyazat", "szegély", "tömörítés", "térkő", "homokbesöprés", "vízelvezetés"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 15,
    materialUnitPrice: 13500,
    laborUnitPrice: 11200,
    otherCost: 180000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Tükörkiemelés", "Geotextília", "Zúzottkő ágyazat", "Szegélyezés", "Tömörítés", "Térkő lerakás", "Homokbesöprés", "Csapadékvíz elvezetés"]),
  },
  {
    id: "landscaping",
    name: "Tereprendezés / kert rendezés",
    discipline: "external_works",
    workTypes: ["new_build", "renovation", "repair"],
    group: "Kert, udvar",
    unit: "m²",
    description: "Kert és udvar rendezése, humuszterítés, kisebb földmunkák.",
    relatedWorks: ["tereprendezés", "humuszterítés", "földmunka", "gereblyézés", "kert előkészítés"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 50,
    materialUnitPrice: 900,
    laborUnitPrice: 1800,
    otherCost: 100000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Tereprendezés", "Humuszterítés", "Földmunka", "Finom tereprendezés", "Gereblyézés", "Kerti hulladék kezelése"]),
  },
  {
    id: "lawn",
    name: "Füvesítés",
    discipline: "external_works",
    workTypes: ["new_build", "renovation"],
    group: "Kert, udvar",
    unit: "m²",
    description: "Füvesítés vagy gyepszőnyeg előkészítő jellegű becslése.",
    relatedWorks: ["talaj előkészítés", "termőföld", "magvetés", "hengerlés", "indító öntözés"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 50,
    materialUnitPrice: 750,
    laborUnitPrice: 1100,
    otherCost: 45000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Talaj előkészítés", "Termőföld terítés", "Fűmag vetés", "Hengerlés", "Indító öntözés", "Gyepszőnyeg opció"]),
  },
  {
    id: "irrigation",
    name: "Öntözőrendszer kiépítés",
    discipline: "external_works",
    workTypes: ["new_build", "renovation"],
    group: "Kert, udvar",
    unit: "m²",
    description: "Automata öntözőrendszer becslése öntözött kertterület alapján.",
    relatedWorks: ["tervezés", "árokásás", "csövezés", "szórófejek", "szelepdoboz", "vezérlő", "beüzemelés"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 50,
    materialUnitPrice: 2800,
    laborUnitPrice: 2400,
    otherCost: 150000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Öntözési zónák tervezése", "Árokásás", "Csőhálózat", "Szórófejek", "Szelepdoboz", "Vezérlő", "Beüzemelés"]),
  },
  {
    id: "tree_planting",
    name: "Fásítás / növénytelepítés",
    discipline: "external_works",
    workTypes: ["new_build", "renovation"],
    group: "Kert, udvar",
    unit: "db",
    description: "Fa, cserje vagy nagyobb növény telepítés egyszerűsített tétele.",
    relatedWorks: ["ültetőgödör", "termőföld", "növény", "karózás", "beiszapolás", "mulcsozás"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 3,
    materialUnitPrice: 18000,
    laborUnitPrice: 8500,
    otherCost: 35000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Ültetőgödör készítés", "Termőföld / komposzt", "Növény beszerzés", "Ültetés", "Karózás", "Beiszapolás", "Mulcsozás"]),
  },
  {
    id: "ac_install_5m",
    name: "Klíma felszerelés 5 m csövezésig",
    discipline: "mechanical",
    workTypes: ["renovation", "new_build"],
    group: "Klíma",
    unit: "db",
    description: "Oldalfali split klíma alap szerelése 5 m csövezésig.",
    relatedWorks: ["beltéri egység", "kültéri egység", "csövezés 5 m-ig", "kondenzvíz", "elektromos bekötés", "vákuumozás", "beüzemelés"],
    quantityBase: "piece",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 65000,
    laborUnitPrice: 95000,
    otherCost: 30000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Beltéri egység felszerelés", "Kültéri egység felszerelés", "Csövezés 5 m-ig", "Kondenzvíz elvezetés", "Elektromos bekötés", "Vákuumozás", "Beüzemelés", "Konzol / tartószerkezet"]),
  },
  {
    id: "ac_install_plus",
    name: "Klíma felszerelés 5 m feletti csövezéssel",
    discipline: "mechanical",
    workTypes: ["renovation", "new_build"],
    group: "Klíma",
    unit: "db",
    description: "Klíma szerelés hosszabb nyomvonal vagy bonyolultabb elhelyezés esetén.",
    relatedWorks: ["alapszerelés", "plusz csövezés", "kábelcsatorna", "kondenzvíz", "magasban szerelés", "beüzemelés"],
    quantityBase: "piece",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 95000,
    laborUnitPrice: 130000,
    otherCost: 45000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Alapszerelés", "Plusz rézcsövezés", "Kábelcsatorna", "Kondenzvíz elvezetés", "Magasban szerelés", "Elektromos bekötés", "Beüzemelés"]),
  },
  {
    id: "solar_pv",
    name: "Napelem telepítés",
    discipline: "renewable_energy",
    workTypes: ["new_build", "renovation"],
    group: "Megújuló energia",
    unit: "kWp",
    description: "Háztartási napelemes rendszer becslése kWp alapján.",
    relatedWorks: ["tartószerkezet", "panelek", "inverter", "DC kábelezés", "AC bekötés", "védelmek", "beüzemelés"],
    quantityBase: "manual",
    quantityMultiplier: 1,
    minQuantity: 3,
    materialUnitPrice: 280000,
    laborUnitPrice: 95000,
    otherCost: 180000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Tartószerkezet", "Panelek elhelyezése", "Inverter", "DC kábelezés", "AC bekötés", "Villamos védelmek", "Beüzemelés", "Dokumentáció"]),
  },
  {
    id: "solar_collector",
    name: "Napkollektor telepítés",
    discipline: "renewable_energy",
    workTypes: ["new_build", "renovation"],
    group: "Megújuló energia",
    unit: "csomag",
    description: "HMV célú napkollektoros rendszer egyszerűsített becslése.",
    relatedWorks: ["kollektor", "tartály", "csövezés", "szivattyú", "vezérlés", "beüzemelés"],
    quantityBase: "package",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 850000,
    laborUnitPrice: 360000,
    otherCost: 160000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Kollektor elhelyezés", "Tartály", "Csövezés", "Szivattyú egység", "Vezérlés", "Hőszigetelés", "Beüzemelés"]),
  },
  {
    id: "heat_pump",
    name: "Hőszivattyú telepítés",
    discipline: "renewable_energy",
    workTypes: ["new_build", "renovation"],
    group: "Megújuló energia",
    unit: "csomag",
    description: "Levegő-víz hőszivattyú telepítésének előzetes becslése.",
    relatedWorks: ["kültéri egység", "beltéri egység", "hidraulika", "puffer", "HMV", "villamos betáp", "beüzemelés"],
    quantityBase: "package",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 2200000,
    laborUnitPrice: 780000,
    otherCost: 350000,
    defaultEnabled: false,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Kültéri egység elhelyezés", "Beltéri egység / hidraulika", "Puffer tartály", "HMV kapcsolat", "Villamos betáp", "Csövezés", "Beüzemelés", "Szabályozás"]),
  },
  {
    id: "other",
    name: "Egyéb / járulékos költség",
    discipline: "other",
    workTypes: ["new_build", "renovation", "repair", "operation"],
    group: "Egyéb",
    unit: "csomag",
    description: "Nem részletezett kisebb tételek, kiszállás, szervezés, járulékos költségek.",
    relatedWorks: ["kiszállás", "anyagmozgatás", "takarítás", "védőeszköz", "szervezés", "adminisztráció"],
    quantityBase: "package",
    quantityMultiplier: 1,
    minQuantity: 1,
    materialUnitPrice: 220000,
    laborUnitPrice: 180000,
    otherCost: 150000,
    defaultEnabled: true,
    source: "dimpro_demo",
    confidence: "demo",
    detailLines: details(["Kiszállás", "Anyagmozgatás", "Takarítás", "Védőeszközök", "Szervezés", "Adminisztráció", "Egyéb kockázati költség"]),
  },
];

export function getCostMajorItem(id: string) {
  return costMajorItems.find((item) => item.id === id);
}

export function getRelatedWorks(id: string) {
  return getCostMajorItem(id)?.relatedWorks ?? [];
}

export function getDetailLines(id: string) {
  return getCostMajorItem(id)?.detailLines ?? [];
}
