"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, Banknote, CheckCircle2, CircleDollarSign, CreditCard, Loader2, PackageCheck, RefreshCw, RotateCcw, ShoppingCart, Store, TriangleAlert } from "lucide-react";
import { AruterBrand, AruterCard, AruterPageShell } from "./AruterShared";

type ApiResult<T>={ok:boolean;data?:T;error?:string;code?:string;context?:CommerceContext};
type CommerceContext={organizationName:string;roleCode:string;permissions:string[]};
type OrderStatus="DRAFT"|"SENT_TO_CASHIER"|"PAID"|"ISSUED"|"CANCELLED";
type OrderSummary={id:string;orderNumber:string;sourceChannel:string;externalReference:string|null;fulfillmentSourceId:string|null;status:OrderStatus;customerName:string;customerType:string;cashierName:string|null;issuerName:string|null;paymentMethod:string|null;pickupAt:string|null;sentToCashierAt:string|null;paidAt:string|null;issuedAt:string|null;createdAt:string};
type OrderItem={id:string;productId:string|null;variantId:string|null;reservationId:string|null;inventoryStatus:"UNRESOLVED"|"RESOLVED"|"RESERVED"|"RELEASED"|"CONSUMED";productName:string;sku:string|null;unit:string;quantity:string;priceNet:string;vatRateBasisPoints:number;storageZone:string|null};
type OrderDetail=OrderSummary&{items:OrderItem[]};
type Options={sources:Array<{id:string;warehouseId:string;code:string;name:string}>;warehouses:Array<{id:string;code:string;name:string}>};

function statusLabel(status:OrderStatus){return status==="SENT_TO_CASHIER"?"Pénztárra vár":status==="PAID"?"Fizetve":status==="ISSUED"?"Kiadva":status==="CANCELLED"?"Törölve":"Vázlat";}
function statusClass(status:OrderStatus){return status==="SENT_TO_CASHIER"?"border-amber-200 bg-amber-50 text-amber-800":status==="PAID"?"border-sky-200 bg-sky-50 text-sky-700":status==="ISSUED"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-slate-200 bg-slate-50 text-slate-600";}
function inventoryLabel(status:OrderItem["inventoryStatus"]){return status==="UNRESOLVED"?"Nincs készlethez kötve":status==="RESOLVED"?"Azonosítva · még nincs foglalva":status==="RESERVED"?"Készlet foglalva":status==="CONSUMED"?"Készlet kiadva":"Foglalás feloldva";}
function inventoryClass(status:OrderItem["inventoryStatus"]){return status==="UNRESOLVED"?"bg-amber-50 text-amber-800":status==="RESOLVED"?"bg-sky-50 text-sky-700":status==="RESERVED"?"bg-teal-50 text-teal-700":status==="CONSUMED"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600";}
function money(value:number){return new Intl.NumberFormat("hu-HU",{style:"currency",currency:"HUF",maximumFractionDigits:0}).format(value);}
function dateTime(value:string|null){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("hu-HU",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d);}

export function CommerceCashierAdmin(){
  const [orders,setOrders]=useState<OrderSummary[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<OrderDetail|null>(null);
  const [context,setContext]=useState<CommerceContext|null>(null),[options,setOptions]=useState<Options>({sources:[],warehouses:[]});
  const [loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
  const [paymentMethod,setPaymentMethod]=useState("CARD"),[cashierName,setCashierName]=useState(""),[issuerName,setIssuerName]=useState(""),[sourceId,setSourceId]=useState("");

  const loadQueue=useCallback(async()=>{setLoading(true);setError(null);try{const [ordersResponse,contextResponse,optionsResponse]=await Promise.all([fetch("/api/v1/commerce/orders?cashierQueue=true&limit=100",{cache:"no-store"}),fetch("/api/v1/commerce/context",{cache:"no-store"}),fetch("/api/v1/commerce/receiving/options",{cache:"no-store"})]);const ordersResult=await ordersResponse.json() as ApiResult<OrderSummary[]>;const contextResult=await contextResponse.json() as ApiResult<never>;const optionsResult=await optionsResponse.json() as ApiResult<Options>;if(!ordersResponse.ok||!ordersResult.ok||!ordersResult.data)throw new Error(ordersResult.error||"A pénztári várólista nem tölthető be.");if(!contextResponse.ok||!contextResult.ok||!contextResult.context)throw new Error(contextResult.error||"A Commerce jogosultság nem tölthető be.");setOrders(ordersResult.data);setContext(contextResult.context);if(optionsResponse.ok&&optionsResult.ok&&optionsResult.data)setOptions(optionsResult.data);setSelectedId(current=>current&&ordersResult.data!.some(order=>order.id===current)?current:ordersResult.data![0]?.id||null);}catch(cause){setError(cause instanceof Error?cause.message:"A pénztári várólista nem tölthető be.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void loadQueue();},[loadQueue]);
  const loadDetail=useCallback(async(orderId:string)=>{setDetailLoading(true);try{const response=await fetch(`/api/v1/commerce/orders/${orderId}`,{cache:"no-store"});const result=await response.json() as ApiResult<OrderDetail>;if(!response.ok||!result.ok||!result.data)throw new Error(result.error||"A rendelés nem tölthető be.");setDetail(result.data);if(result.data.fulfillmentSourceId)setSourceId(result.data.fulfillmentSourceId);}catch(cause){setError(cause instanceof Error?cause.message:"A rendelés nem tölthető be.");}finally{setDetailLoading(false);}},[]);
  useEffect(()=>{if(selectedId)void loadDetail(selectedId);else setDetail(null);},[selectedId,loadDetail]);

  const selected=useMemo(()=>orders.find(order=>order.id===selectedId)||null,[orders,selectedId]);
  const canReserve=context?.permissions.includes("commerce.order.write")&&context.permissions.includes("commerce.inventory.move");
  const canPay=context?.permissions.includes("commerce.order.pay");
  const canIssue=context?.permissions.includes("commerce.order.issue");
  const totals=useMemo(()=>{const items=detail?.items||[];const net=items.reduce((sum,item)=>sum+Number(item.quantity)*Number(item.priceNet),0);const gross=items.reduce((sum,item)=>sum+Number(item.quantity)*Number(item.priceNet)*(1+item.vatRateBasisPoints/10000),0);return{net,gross};},[detail]);
  const unresolved=detail?.items.filter(item=>item.inventoryStatus==="UNRESOLVED")||[];
  const needsReserve=detail?.items.filter(item=>item.variantId&&item.inventoryStatus==="RESOLVED")||[];

  async function action(path:string,body:Record<string,unknown>,key:string){if(!selectedId||busy)return;setBusy(true);setError(null);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json","idempotency-key":key},body:JSON.stringify({...body,idempotencyKey:key})});const result=await response.json() as ApiResult<unknown>;if(!response.ok||!result.ok)throw new Error(result.error||"A művelet sikertelen.");await loadQueue();await loadDetail(selectedId);}catch(cause){setError(cause instanceof Error?cause.message:"A művelet sikertelen.");}finally{setBusy(false);}}
  async function reserve(){if(!selectedId||!sourceId)return;await action(`/api/v1/commerce/orders/${selectedId}/reserve`,{sourceId,expiresAt:new Date(Date.now()+2*60*60*1000).toISOString()},`cashier-reserve-${selectedId}`);}
  async function pay(){if(!selectedId)return;await action(`/api/v1/commerce/orders/${selectedId}/status`,{status:"PAID",paymentMethod,cashierName:cashierName.trim()||"Pénztáros"},`cashier-paid-${selectedId}`);}
  async function issue(){if(!selectedId)return;await action(`/api/v1/commerce/orders/${selectedId}/status`,{status:"ISSUED",issuerName:issuerName.trim()||"Kiadó"},`cashier-issued-${selectedId}`);}

  return <AruterPageShell>
    <header className="border-b border-slate-200 bg-white px-4 py-4 sm:px-6"><div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><AruterBrand compact/><span className="hidden h-10 w-px bg-slate-200 sm:block"/><div><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Commerce Core</p><h1 className="text-xl font-black text-slate-900">Központi pénztár</h1></div></div><div className="flex items-center gap-2"><span className="hidden rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-black text-slate-600 md:inline-flex">{context?.roleCode||"—"}</span>{context?.permissions.includes("commerce.order.reconcile")&&<Link href="/aruter/admin/egyeztetes" className="hidden h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 font-black text-slate-700 sm:inline-flex"><RotateCcw size={17}/> Egyeztetés</Link>}<Link href="/aruter/admin/termekek" className="inline-flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 font-black text-slate-700"><Store size={17}/> Admin</Link></div></div></header>
    <div className="mx-auto max-w-[1600px] px-4 py-5 sm:px-6">
      {error&&<div className="mb-4 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertCircle size={20}/><div><b>Pénztári állapot</b><p className="mt-1 text-sm font-semibold">{error}</p></div></div>}
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_440px]">
        <AruterCard className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="text-xl font-black">Pénztárra váró rendelések</h2><p className="text-sm font-semibold text-slate-500">{loading?"Betöltés...":`${orders.length} aktív rendelés`}</p></div><button onClick={()=>void loadQueue()} className="rounded-xl border border-slate-200 p-2.5 text-slate-600"><RefreshCw size={18}/></button></div>
          <div className="divide-y divide-slate-100">{orders.map(order=><button key={order.id} type="button" onClick={()=>setSelectedId(order.id)} className={`flex w-full items-center gap-4 p-4 text-left hover:bg-teal-50/40 ${selectedId===order.id?"bg-teal-50/70":""}`}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><ShoppingCart size={20}/></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><b className="truncate">{order.orderNumber}</b>{order.sourceChannel==="EXTERNAL_MARKETPLACE"&&<span className="rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-black text-violet-700">Külső Árutér</span>}</span><span className="mt-0.5 block truncate text-xs font-semibold text-slate-500">{order.customerName} · {dateTime(order.sentToCashierAt||order.createdAt)}</span></span><span className={`rounded-full border px-2.5 py-1 text-xs font-black ${statusClass(order.status)}`}>{statusLabel(order.status)}</span></button>)}</div>
          {!loading&&!orders.length&&<div className="p-12 text-center"><CheckCircle2 className="mx-auto text-emerald-300" size={40}/><b className="mt-3 block">Nincs pénztárra váró rendelés.</b><p className="mt-1 text-sm font-semibold text-slate-500">Az új külső és belső rendelések itt jelennek meg.</p></div>}
        </AruterCard>

        <AruterCard className="h-fit p-5 xl:sticky xl:top-5">{detailLoading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="animate-spin text-teal-700"/></div>:detail&&selected?<div>
          <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-slate-400">Rendelés</p><h2 className="mt-1 text-2xl font-black">{detail.orderNumber}</h2><p className="mt-1 text-sm font-semibold text-slate-500">{detail.customerName}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs font-black ${statusClass(detail.status)}`}>{statusLabel(detail.status)}</span></div>
          <div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs font-black text-slate-400">Nettó</p><b className="mt-1 block text-xl">{money(totals.net)}</b></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs font-black text-slate-400">Bruttó</p><b className="mt-1 block text-xl">{money(totals.gross)}</b></div></div>
          {unresolved.length>0&&<div className="mt-3 flex gap-2 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-amber-900"><TriangleAlert size={18} className="shrink-0"/><div><b className="text-sm">{unresolved.length} tétel nincs készlethez kötve</b><p className="mt-0.5 text-xs font-semibold">A pénztárban továbbra is látható. A készletazonosítás külön rendezhető.</p></div></div>}
          <div className="mt-4 space-y-2">{detail.items.map(item=><div key={item.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b className="block truncate text-sm">{item.productName}</b><p className="mt-0.5 text-xs font-semibold text-slate-500">{item.quantity} {item.unit.toLowerCase()} · {item.sku||"nincs SKU"}{item.storageZone?` · ${item.storageZone}`:""}</p></div><b className="shrink-0 text-sm">{money(Number(item.quantity)*Number(item.priceNet))}</b></div><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] font-black ${inventoryClass(item.inventoryStatus)}`}>{inventoryLabel(item.inventoryStatus)}</span></div>)}</div>
          {needsReserve.length>0&&<div className="mt-4 rounded-2xl border border-sky-200 bg-sky-50 p-4"><b className="text-sm text-sky-900">{needsReserve.length} azonosított tétel készletfoglalásra vár</b>{canReserve?<><select value={sourceId} onChange={e=>setSourceId(e.target.value)} className="mt-3 h-10 w-full rounded-xl border border-sky-200 bg-white px-3 text-sm"><option value="">Készletforrás...</option>{options.sources.map(source=><option key={source.id} value={source.id}>{source.name} · {source.code}</option>)}</select><button type="button" disabled={busy||!sourceId} onClick={()=>void reserve()} className="mt-2 h-10 w-full rounded-xl bg-sky-700 text-sm font-black text-white disabled:bg-slate-300">Készlet foglalása</button></>:<p className="mt-1 text-xs font-semibold text-sky-700">A készletfoglalást raktári/vezetői jogosultsággal lehet elvégezni.</p>}</div>}
          {detail.status==="SENT_TO_CASHIER"&&<div className="mt-4 rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2"><CircleDollarSign size={18} className="text-teal-700"/><b>Fizetés rögzítése</b></div>{canPay?<><div className="mt-3 grid grid-cols-2 gap-2"><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} className="h-10 rounded-xl border border-slate-200 px-2 text-sm"><option value="CARD">Bankkártya</option><option value="CASH">Készpénz</option><option value="TRANSFER">Átutalás</option><option value="LATER">Későbbi fizetés</option></select><input value={cashierName} onChange={e=>setCashierName(e.target.value)} placeholder="Pénztáros neve" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/></div><button type="button" onClick={()=>void pay()} disabled={busy} className="mt-2 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-teal-700 font-black text-white disabled:bg-slate-300">{paymentMethod==="CARD"?<CreditCard size={17}/>:<Banknote size={17}/>} Fizetve</button></>:<p className="mt-2 text-xs font-semibold text-slate-500">Ehhez a szerepkörhöz nincs fizetés-rögzítési jogosultság.</p>}</div>}
          {detail.status==="PAID"&&<div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-2 text-emerald-800"><PackageCheck size={18}/><b>Fizetve · kiadásra kész</b></div><p className="mt-1 text-xs font-semibold text-emerald-700">Pénztáros: {detail.cashierName||"—"} · {detail.paymentMethod||"—"}</p>{canIssue?<><input value={issuerName} onChange={e=>setIssuerName(e.target.value)} placeholder="Kiadó neve" className="mt-3 h-10 w-full rounded-xl border border-emerald-200 bg-white px-3 text-sm"/><button type="button" disabled={busy||needsReserve.length>0} onClick={()=>void issue()} className="mt-2 h-11 w-full rounded-xl bg-emerald-700 font-black text-white disabled:bg-slate-300">Kiadás rögzítése</button></>:<p className="mt-2 text-xs font-semibold">A kiadást külön raktári jogosultsággal lehet rögzíteni.</p>}</div>}
        </div>:<div className="flex min-h-64 flex-col items-center justify-center text-center"><ShoppingCart className="text-slate-300" size={38}/><b className="mt-3">Válasszon rendelést</b><p className="mt-1 text-sm font-semibold text-slate-500">A kosár tételei és pénztári műveletek itt jelennek meg.</p></div>}</AruterCard>
      </div>
    </div>
  </AruterPageShell>;
}
