import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
const require=createRequire(import.meta.url); const here=path.dirname(fileURLToPath(import.meta.url)); const root=path.resolve(here,"..");
const {WORKER_OPTIONS,cloneDefaultConfig,sanitizeConfig}=require(path.join(root,"src/config/defaults.cjs"));
const {createPasswordRecord,verifyPassword}=require(path.join(root,"src/security/password-store.cjs"));
const pkg=JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8"));
const main=fs.readFileSync(path.join(root,"src/main.cjs"),"utf8");
const html=fs.readFileSync(path.join(root,"src/renderer/index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"src/renderer/styles.css"),"utf8");
const renderer=fs.readFileSync(path.join(root,"src/renderer/renderer.js"),"utf8");
const config=cloneDefaultConfig(); let n=0;
function check(label,fn){fn();n++;console.log(`PASS ${String(n).padStart(2,"0")} ${label}`)}
check("package version 0.1.4",()=>assert.equal(pkg.version,"0.1.4"));
check("separate Developer Grid package",()=>assert.equal(pkg.name,"@dimpro/benjadmin-developer-grid-desktop"));
check("separate Windows appId",()=>assert.equal(pkg.build.appId,"hu.dimpro.benjadmin.developergrid"));
check("separate EXE artifact name",()=>assert.match(pkg.build.win.artifactName,/BENJADMIN-Developer-Grid/));
check("custom DIMPRO Windows icon configured",()=>{assert.equal(pkg.build.win.icon,"src/assets/app-icon.ico");const iconPath=path.join(root,pkg.build.win.icon);assert.equal(fs.existsSync(iconPath),true);const ico=fs.readFileSync(iconPath);const count=ico.readUInt16LE(4);let has256=false;for(let i=0;i<count;i+=1){const pos=6+i*16;const w=ico[pos]||256;const h=ico[pos+1]||256;if(w===256&&h===256)has256=true}assert.equal(has256,true)});
check("Windows resource editing stays enabled while signing is disabled",()=>{assert.equal(pkg.build.win.signExecutable,false);assert.notEqual(pkg.build.win.signAndEditExecutable,false)});
check("exactly four primary cells",()=>assert.equal(config.cells.length,4));
check("fixed visual worker order",()=>assert.deepEqual(config.cells.map(x=>x.workerCode),["ARMINAI","OUTMINAI","BENAI","JAZMINAI"]));
check("fixed visual labels",()=>assert.deepEqual(config.cells.map(x=>x.label),["ÁrminAI","OutminAI","BenjáminAI","JázminAI"]));
check("worker option order matches layout",()=>assert.deepEqual(WORKER_OPTIONS,["ARMINAI","OUTMINAI","BENAI","JAZMINAI"]));
check("central control workspace visible by default",()=>assert.equal(config.contextWorkspace.visible,true));
check("central control workspace docked by default",()=>assert.equal(config.contextWorkspace.detached,false));
check("05 DevminAI prepared",()=>assert.equal(config.centralChat.label,"DevminAI"));
check("Developer Grid title rendered",()=>assert.match(html,/BENJADMIN Developer Grid/));
check("central BENJADMIN control title rendered",()=>assert.match(html,/BENJADMIN FEJLESZTŐI VEZÉRLŐPULT/));
check("01 ÁrminAI DOM mapping",()=>assert.match(html,/cell-1[^>]+data-worker-code="ARMINAI"/));
check("02 OutminAI DOM mapping",()=>assert.match(html,/cell-2[^>]+data-worker-code="OUTMINAI"/));
check("03 BenjáminAI backend-compatible DOM mapping",()=>assert.match(html,/cell-3[^>]+data-worker-code="BENAI"/));
check("04 JázminAI DOM mapping",()=>assert.match(html,/cell-4[^>]+data-worker-code="JAZMINAI"/));
check("center-column grid capability inherited",()=>assert.match(css,/body\.has-context-workspace \.chat-grid/));
check("separate ChatGPT partition",()=>assert.match(main,/persist:benjadmin-developer-grid-chatgpt/));
check("separate LocalAppData executable",()=>assert.match(main,/BENJADMIN Developer Grid.*BENJADMIN-Developer-Grid\.exe/));
check("separate local config file",()=>assert.match(main,/developer-grid-config\.json/));
check("DevminAI central title",()=>assert.match(main,/05 DevminAI/));
check("DevminAI generic asset used",()=>assert.match(main,/devminai\.svg/));
check("ChatGPT views sandboxed",()=>{assert.match(main,/nodeIntegration: false/);assert.match(main,/contextIsolation: true/);assert.match(main,/sandbox: true/);assert.match(main,/webSecurity: true/)});
check("workspace lock destroys chat views",()=>assert.match(main,/destroyChatViews\(\)/));
check("Windows screen lock hook",()=>assert.match(main,/powerMonitor\.on\("lock-screen"/));
check("local password uses scrypt",()=>{const r=createPasswordRecord("DeveloperGrid-2026!");assert.equal(r.algorithm,"scrypt");assert.equal(verifyPassword("DeveloperGrid-2026!",r),true)});
check("foreign ChatGPT host rejected",()=>{const x=sanitizeConfig({cells:[{url:"https://example.com/x"}]});assert.equal(x.cells[0].url,"https://chatgpt.com/")});
check("DEV BENJADMIN HTTPS default",()=>assert.equal(config.benjadminBaseUrl,"https://admin.dev.dimpro.hu"));
check("PROD text remains deny",()=>assert.match(html,/DEV · PROD DENY/));
check("native Developer Grid delta is primary live transport",()=>{const x=fs.readFileSync(path.join(root,"src/live/benjadmin-live-client.cjs"),"utf8");assert.match(x,/\/api\/dev\/grid\/foundation/);assert.match(x,/state\?after=/);assert.match(x,/events\?limit=100/);assert.match(x,/fullSnapshotPollingAllowed !== false/)});
check("legacy ChatGrid snapshot is one-shot fallback only",()=>{const x=fs.readFileSync(path.join(root,"src/live/benjadmin-live-client.cjs"),"utf8");assert.equal((x.match(/\/api\/dev\/chatgrid\/live/g)||[]).length,1);assert.match(x,/legacyBootstrapUsed/)});
check("central workspace renderer is present",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.ok(x.length>1000)});
check("central workspace renders immediately before remote context fetch",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.match(x,/render\(\);\s*setNotice\("Vezérlőpult kapcsolódás/)});
check("central workspace renders pairing error instead of blank body",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.match(x,/contextErrorMessage/);assert.match(x,/párosítsd a Developer Gridet/);assert.match(x,/if\(!result\?\.ok\)\{state\.notice=contextErrorMessage\(result\?\.error\);render\(\)/)});
check("ChatGrid source product not overwritten by package identity",()=>assert.ok(!pkg.name.includes("chatgrid")));
const contextWorkspaceSource=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");
check("header handoff is stage-aware",()=>assert.match(contextWorkspaceSource,/idleStageAllowsHandoff=stageIndex===2\|\|stageIndex===6/));
check("stage 6 exposes V2 save wording",()=>assert.match(contextWorkspaceSource,/V2 MENTÉS/));
check("new handoff only in closure stage",()=>assert.match(contextWorkspaceSource,/stateName!=="SAVED"\|\|stageIndex!==6/));
check("renderer publishes one authoritative stage index",()=>assert.match(renderer,/cell\.dataset\.workStageIndex/));
check("stage 1 actions task context checkpoint",()=>assert.match(renderer,/1: \[\{ id: "current-task".*"context".*"checkpoint"/s));
check("stage 2 actions task checkpoint",()=>assert.match(renderer,/2: \[\{ id: "current-task".*"checkpoint"/s));
check("stage 3 actions task tests checkpoint",()=>assert.match(renderer,/3: \[\{ id: "current-task".*"tests".*"checkpoint"/s));
check("stage 4 actions task review checkpoint",()=>assert.match(renderer,/4: \[\{ id: "current-task".*"review".*"checkpoint"/s));
check("stage 5 actions build runtime checkpoint",()=>assert.match(renderer,/5: \[\{ id: "build-runtime".*"checkpoint"/s));
check("stage 6 leaves header to handoff controls",()=>assert.match(renderer,/6: \[\]/));
const stagePrompt=fs.readFileSync(path.join(root,"src/stage-actions-prompt-builder.cjs"),"utf8");
check("checkpoint prompt is DEV only",()=>assert.match(stagePrompt,/DEV ONLY · PROD DENY/));
check("build prompt forbids raw build",()=>assert.match(stagePrompt,/build:raw és kerülő\/párhuzamos build tilos/));
check("stage action IPC is exposed",()=>{const preload=fs.readFileSync(path.join(root,"src/preload.cjs"),"utf8");assert.match(preload,/prepareStageAction/);assert.match(main,/stage-action:prepare/)});
const guideSource=fs.readFileSync(path.join(root,"src/guide/default-guide.cjs"),"utf8");
check("guide uses Developer Grid product name",()=>{assert.match(guideSource,/BENJADMIN DEVELOPER GRID/);assert.doesNotMatch(guideSource,/BENJADMIN CHATGRID/)});
check("guide fixed shortcut layout matches cells",()=>{assert.match(guideSource,/Ctrl\+Alt\+1 — ÁrminAI cella/);assert.match(guideSource,/Ctrl\+Alt\+3 — BenjáminAI cella/)});
check("05 is DevminAI not human BenjAdmin",()=>{assert.match(guideSource,/05 DevminAI/);assert.match(fs.readFileSync(path.join(root,"src/renderer/central.html"),"utf8"),/Nem emberi döntéshozó/)});
check("visible shell and guide use Developer Grid branding",()=>{assert.doesNotMatch(html,/BENJADMIN CHATGRID/);assert.doesNotMatch(fs.readFileSync(path.join(root,"src/renderer/guide.html"),"utf8"),/BENJADMIN CHATGRID/)});
console.log(`BENJADMIN Developer Grid Desktop v0.1.4 acceptance PASS · ${n}/${n}`);
