import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
const require=createRequire(import.meta.url); const here=path.dirname(fileURLToPath(import.meta.url)); const root=path.resolve(here,"..");
const {WORKER_OPTIONS,cloneDefaultConfig,sanitizeConfig}=require(path.join(root,"src/config/defaults.cjs"));
const {createPasswordRecord,verifyPassword}=require(path.join(root,"src/security/password-store.cjs"));
const pkg=JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8"));
const main=fs.readFileSync(path.join(root,"src/main.cjs"),"utf8");
const html=fs.readFileSync(path.join(root,"src/renderer/index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"src/renderer/styles.css"),"utf8");
const renderer=fs.readFileSync(path.join(root,"src/renderer/renderer.js"),"utf8");
const contextWorkspaceSource=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");
const config=cloneDefaultConfig(); let n=0;
function check(label,fn){fn();n++;console.log(`PASS ${String(n).padStart(2,"0")} ${label}`)}
check("package version 0.1.22",()=>assert.equal(pkg.version,"0.1.22"));
check("separate Developer Grid package",()=>assert.equal(pkg.name,"@dimpro/benjadmin-developer-grid-desktop"));
check("separate Windows appId",()=>assert.equal(pkg.build.appId,"hu.dimpro.benjadmin.developergrid"));
check("separate EXE artifact name",()=>assert.match(pkg.build.win.artifactName,/BENJADMIN-Developer-Grid/));
check("custom DIMPRO Windows icon configured",()=>{assert.equal(pkg.build.win.icon,"src/assets/app-icon.ico");const iconPath=path.join(root,pkg.build.win.icon);assert.equal(fs.existsSync(iconPath),true);const ico=fs.readFileSync(iconPath);const count=ico.readUInt16LE(4);let has256=false;for(let i=0;i<count;i+=1){const pos=6+i*16;const w=ico[pos]||256;const h=ico[pos+1]||256;if(w===256&&h===256)has256=true}assert.equal(has256,true)});
check("Windows resource editing stays enabled while signing is disabled",()=>{assert.equal(pkg.build.win.signExecutable,false);assert.notEqual(pkg.build.win.signAndEditExecutable,false)});
check("exactly four primary cells",()=>assert.equal(config.cells.length,4));
check("fixed visual worker order",()=>assert.deepEqual(config.cells.map(x=>x.workerCode),["ARMINAI","OUTMINAI","BENAI","JAZMINAI"]));
check("fixed visual labels",()=>assert.deepEqual(config.cells.map(x=>x.label),["ÁrminAI","OutminAI","BenjáminAI","JázminAI"]));
check("worker option order matches layout",()=>assert.deepEqual(WORKER_OPTIONS,["ARMINAI","OUTMINAI","BENAI","JAZMINAI"]));
check("central control workspace closed by default for full-width chat cells",()=>assert.equal(config.contextWorkspace.visible,false));
check("central control workspace docked by default",()=>assert.equal(config.contextWorkspace.detached,false));
check("05 DevminAI prepared",()=>assert.equal(config.centralChat.label,"DevminAI"));
check("Developer Grid title rendered",()=>assert.match(html,/BENJADMIN Developer Grid/));
check("central BENJADMIN control title rendered",()=>assert.match(html,/BENJADMIN FEJLESZTŐI VEZÉRLŐPULT/));
check("01 ÁrminAI DOM mapping",()=>assert.match(html,/cell-1[^>]+data-worker-code="ARMINAI"/));
check("02 OutminAI DOM mapping",()=>assert.match(html,/cell-2[^>]+data-worker-code="OUTMINAI"/));
check("03 BenjáminAI backend-compatible DOM mapping",()=>assert.match(html,/cell-3[^>]+data-worker-code="BENAI"/));
check("04 JázminAI DOM mapping",()=>assert.match(html,/cell-4[^>]+data-worker-code="JAZMINAI"/));
check("center-column grid capability inherited",()=>assert.match(css,/body\.has-context-workspace \.chat-grid/));
check("separate ChatGPT partition",()=>assert.match(main,/persist:benjadmin-developer-grid-chatgpt/));
check("separate LocalAppData executable",()=>assert.match(main,/BENJADMIN Developer Grid.*BENJADMIN-Developer-Grid\.exe/));
check("separate local config file",()=>assert.match(main,/developer-grid-config\.json/));
check("DevminAI central title",()=>assert.match(main,/05 DevminAI/));
check("DevminAI uploaded PNG asset used",()=>{assert.match(main,/devminai\.png/);assert.equal(fs.existsSync(path.join(root,"src/assets/team/devminai.png")),true)});
check("ChatGPT views sandboxed",()=>{assert.match(main,/nodeIntegration: false/);assert.match(main,/contextIsolation: true/);assert.match(main,/sandbox: true/);assert.match(main,/webSecurity: true/)});
check("workspace lock destroys chat views",()=>assert.match(main,/destroyChatViews\(\)/));
check("Windows screen lock hook",()=>assert.match(main,/powerMonitor\.on\("lock-screen"/));
check("local password uses scrypt",()=>{const r=createPasswordRecord("DeveloperGrid-2026!");assert.equal(r.algorithm,"scrypt");assert.equal(verifyPassword("DeveloperGrid-2026!",r),true)});
check("foreign ChatGPT host rejected",()=>{const x=sanitizeConfig({cells:[{url:"https://example.com/x"}]});assert.equal(x.cells[0].url,"https://chatgpt.com/")});
check("DEV BENJADMIN HTTPS default",()=>assert.equal(config.benjadminBaseUrl,"https://admin.dev.dimpro.hu"));
check("PROD text remains deny",()=>assert.match(html,/DEV · PROD DENY/));
check("native Developer Grid delta is primary live transport",()=>{const x=fs.readFileSync(path.join(root,"src/live/benjadmin-live-client.cjs"),"utf8");assert.match(x,/\/api\/dev\/grid\/foundation/);assert.match(x,/state\?after=/);assert.match(x,/events\?limit=100/);assert.match(x,/fullSnapshotPollingAllowed !== false/)});
check("legacy ChatGrid snapshot is one-shot fallback only",()=>{const x=fs.readFileSync(path.join(root,"src/live/benjadmin-live-client.cjs"),"utf8");assert.equal((x.match(/\/api\/dev\/chatgrid\/live/g)||[]).length,1);assert.match(x,/legacyBootstrapUsed/)});
check("central workspace renderer is present",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.ok(x.length>1000)});
check("central workspace renders immediately before remote context fetch",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.match(x,/render\(\);\s*setNotice\("Vezérlőpult kapcsolódás/)});
check("central workspace renders pairing error instead of blank body",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.match(x,/contextErrorMessage/);assert.match(x,/párosítsd a Developer Gridet/);assert.match(x,/if\(!result\?\.ok\)\{state\.notice=contextErrorMessage\(result\?\.error\);render\(\)/)});
check("daily work-start composer visible",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.match(x,/Mit fejlesszünk\?/);assert.match(x,/MUNKA INDÍTÁSA/);assert.match(x,/workStartPrompt/)});
check("daily work-start preserves draft and uses explicit submit",()=>{const x=fs.readFileSync(path.join(root,"src/renderer/context-workspace.js"),"utf8");assert.match(x,/workStartDraft/);assert.match(x,/e\.ctrlKey/);assert.match(x,/if\(state\.workStartBusy\)return/)});

check("header exposes compact ChatGPT refresh lifecycle",()=>{assert.match(html,/headerChatStatus/);assert.match(html,/headerChatRefreshButton/);assert.doesNotMatch(html,/id="headerChatUpdated"/);assert.doesNotMatch(html,/id="headerChatVersion"/);assert.match(renderer,/formatChatRefreshFullTime/);});
check("control workspace is forced closed at app startup",()=>assert.match(main,/contextWorkspace = \{ \.\.\.config\.contextWorkspace, visible: false, detached: false \}/));
check("control center shows BUILD01 and BUILD02 runner health",()=>{assert.match(contextWorkspaceSource,/BUILD RUNNER POOL/);assert.match(contextWorkspaceSource,/build01/);assert.match(contextWorkspaceSource,/build02/);assert.match(contextWorkspaceSource,/getSystemHealth/);});
check("control center shows Diagnostic Evidence and review gates",()=>{assert.match(contextWorkspaceSource,/DIAGNOSTIC EVIDENCE ENGINE/);assert.match(contextWorkspaceSource,/REVIEW READINESS/);assert.match(contextWorkspaceSource,/BUILD GATE/);assert.match(contextWorkspaceSource,/CLOSURE \/ HANDOFF/);});
check("control center exposes explicit VGuard review without automatic provider spend",()=>{assert.match(contextWorkspaceSource,/FÜGGETLEN REVIEW INDÍTÁSA/);assert.match(contextWorkspaceSource,/requestDeveloperGridVGuardReview/);assert.doesNotMatch(contextWorkspaceSource,/setInterval\([^)]*requestDeveloperGridVGuardReview/);});
check("work-start requires explicit coding worker",()=>{assert.doesNotMatch(contextWorkspaceSource,/Automatikus · Central Core választ/);assert.match(contextWorkspaceSource,/Válassz kódmérnököt/);assert.match(contextWorkspaceSource,/Automatikus worker-kiosztás nincs/);});
const taskLaunchPrompt=fs.readFileSync(path.join(root,"src/task-launch/prompt-builder.cjs"),"utf8");
check("Task Launch V3 carries authoritative launch packet and BOOT ACK",()=>{assert.match(taskLaunchPrompt,/TASK_LAUNCH_V3/);assert.match(taskLaunchPrompt,/LAUNCH PACKET · AUTHORITATIVE/);assert.match(taskLaunchPrompt,/BOOT ACKNOWLEDGEMENT/);assert.match(taskLaunchPrompt,/SOURCE_BASELINE_MISMATCH/);});
check("ChatGrid source product not overwritten by package identity",()=>assert.ok(!pkg.name.includes("chatgrid")));
check("header handoff is stage-aware",()=>assert.match(contextWorkspaceSource,/idleStageAllowsHandoff=stageIndex===2\|\|stageIndex===6/));
check("stage 6 exposes V2 save wording",()=>assert.match(contextWorkspaceSource,/V2 MENTÉS/));
check("new handoff only in closure stage",()=>assert.match(contextWorkspaceSource,/stateName!=="SAVED"\|\|stageIndex!==6/));
check("renderer publishes one authoritative stage index",()=>assert.match(renderer,/cell\.dataset\.workStageIndex/));
check("stage 1 actions task context checkpoint",()=>assert.match(renderer,/1: \[\{ id: "current-task".*"context".*"checkpoint"/s));
check("stage 2 actions task checkpoint",()=>assert.match(renderer,/2: \[\{ id: "current-task".*"checkpoint"/s));
check("stage 3 actions task tests checkpoint",()=>assert.match(renderer,/3: \[\{ id: "current-task".*"tests".*"checkpoint"/s));
check("stage 4 actions task review checkpoint",()=>assert.match(renderer,/4: \[\{ id: "current-task".*"review".*"checkpoint"/s));
check("stage 5 actions build runtime checkpoint",()=>assert.match(renderer,/5: \[\{ id: "build-runtime".*"checkpoint"/s));
check("stage 6 leaves header to handoff controls",()=>assert.match(renderer,/6: \[\]/));
const stagePrompt=fs.readFileSync(path.join(root,"src/stage-actions-prompt-builder.cjs"),"utf8");
check("checkpoint prompt is DEV only",()=>assert.match(stagePrompt,/DEV ONLY · PROD DENY/));
check("build prompt forbids raw build and DEV-host fallback",()=>{assert.match(stagePrompt,/build:raw/);assert.match(stagePrompt,/DEV-host FULL BUILD fallback/);assert.match(stagePrompt,/FULL BUILD-et a worker NEM indíthat/);});
check("stage action IPC is exposed",()=>{const preload=fs.readFileSync(path.join(root,"src/preload.cjs"),"utf8");assert.match(preload,/prepareStageAction/);assert.match(main,/stage-action:prepare/)});
const guideSource=fs.readFileSync(path.join(root,"src/guide/default-guide.cjs"),"utf8");
check("guide uses Developer Grid product name",()=>{assert.match(guideSource,/BENJADMIN DEVELOPER GRID/);assert.doesNotMatch(guideSource,/BENJADMIN CHATGRID/)});
check("guide fixed shortcut layout matches cells",()=>{assert.match(guideSource,/Ctrl\+Alt\+1 — ÁrminAI cella/);assert.match(guideSource,/Ctrl\+Alt\+3 — BenjáminAI cella/)});
check("05 is DevminAI not human BenjAdmin",()=>{assert.match(guideSource,/05 DevminAI/);assert.match(fs.readFileSync(path.join(root,"src/renderer/central.html"),"utf8"),/Nem emberi döntéshozó/)});
const centralHtml=fs.readFileSync(path.join(root,"src/renderer/central.html"),"utf8");
const centralCss=fs.readFileSync(path.join(root,"src/renderer/central.css"),"utf8");
check("DevminAI avatar opens centered profile card",()=>{assert.match(centralHtml,/central-profile-card/);assert.match(centralHtml,/profileBackdrop/);assert.match(centralCss,/place-items:center/);assert.doesNotMatch(centralCss,/\.central-profile \{ position:fixed; inset:52px 0 0/)});
check("DevminAI chat watermark uses uploaded PNG",()=>{assert.match(main,/DEVMINAI: path\.join\(__dirname, "assets", "team", "devminai\.png"\)/);assert.match(main,/cell\.id === "central".*AVATAR_ASSETS\.DEVMINAI/s);assert.match(main,/extension === "\.png" \? "image\/png"/)});
check("visible shell and guide use Developer Grid branding",()=>{assert.doesNotMatch(html,/BENJADMIN CHATGRID/);assert.doesNotMatch(fs.readFileSync(path.join(root,"src/renderer/guide.html"),"utf8"),/BENJADMIN CHATGRID/)});

check("split2 keeps Central Core docked",()=>{assert.match(main,/function contextWorkspaceDocked\(\)[\s\S]*!maximizedCellId\);/);assert.doesNotMatch(main,/contextWorkspaceDocked[\s\S]{0,220}layoutMode !== "split2"/);assert.match(main,/getSplitDockedContextRect/);assert.match(css,/body\.has-split2\.has-context-workspace \.chat-grid/);});
check("work-start preserves existing worker conversation",()=>{assert.match(main,/captureWorkerConversationGuards/);assert.match(main,/preserveWorkerConversationsAfterWorkStart\(conversationGuards\)/);assert.match(main,/restoreWorkerConversationGuard/);});
check("ChatGPT copy button clipboard write is origin scoped",()=>{assert.match(main,/clipboard-sanitized-write/);assert.match(main,/clipboard-write/);assert.match(main,/return isChatGptUrl\(origin\)/);assert.doesNotMatch(main,/clipboard-read/);});
check("large paste supports 250k with chunking and timing",()=>{assert.match(main,/LARGE_PASTE_THRESHOLD = 6000/);assert.match(main,/LARGE_PASTE_MAX_CHARS = 250000/);assert.match(main,/LARGE_PASTE_CHUNK = 12000/);assert.match(main,/elapsedMs/);assert.match(renderer,/nagy beillesztés kész/);});
check("disabled controls never advertise waiting cursor",()=>assert.doesNotMatch(css,/cursor:\s*wait/));
check("Central Core has emphasized enterprise surface and readable light controls",()=>{assert.match(css,/Developer Grid v0\.1\.7 RC polish/);assert.match(css,/:root\[data-theme="light"\] \.context-workspace/);assert.match(css,/\.cw-work-actions button[\s\S]*background:#0b9874/);});

check("BenjáminAI profile is integrated code engineer",()=>{assert.match(renderer,/title: "Integrált AI kódmérnök · full-stack \/ rendszerintegráció"/);assert.match(renderer,/category: "Integrált kódmérnök"/);assert.doesNotMatch(renderer,/Fejlesztésirányító AI · koordinátor/);});
check("all four worker headers expose code-engineer role badge",()=>{assert.equal((html.match(/data-role="worker-role"/g)||[]).length,4);assert.match(html,/INTEGRÁLT KÓDMÉRNÖK/);assert.match(renderer,/WORKER_ROLE_LABELS/);});
check("Central Core owns coordination wording",()=>{assert.match(contextWorkspaceSource,/Central Core koordináció/);assert.doesNotMatch(contextWorkspaceSource,/BenAI koordináció/);assert.match(guideSource,/Central Core \/ Grid Orchestrator/);});
check("worker headers expose engineering phase status",()=>{for(const label of ["ELEMZÉS","FEJLESZT","TESZTEL","ELLENŐRIZ","BUILD","LEZÁRÁS"])assert.match(renderer,new RegExp(label));});
console.log(`BENJADMIN Developer Grid Desktop v0.1.22 DEV acceptance PASS · ${n}/${n}`);
