import type { CalendarEvent } from "@/app/lib/calendar/types";

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: "event-1",
    title: "Projektindító egyeztetés",
    start: "2026-05-18T09:00:00",
    end: "2026-05-18T10:00:00",
    className: "dimpro-event-blue",
    meetingType: "Microsoft Teams-értekezlet",
    person: "Keserű Benjamin",
    location: "Online",
    description: "Projektindító státusz és heti feladatok egyeztetése.",
    status: "Tervezett",
    recurrence: "weekly",
    externalProvider: "none",
    externalEventId: "",
    syncStatus: "none",
    lastSyncedAt: null,
  },
  {
    id: "event-2",
    title: "Helyszíni bejárás",
    start: "2026-05-19T11:00:00",
    end: "2026-05-19T12:30:00",
    className: "dimpro-event-cyan",
    meetingType: "Helyszíni egyeztetés",
    person: "Mérnöki csapat",
    location: "Szekszárd",
    description: "Bejárás és műszaki kérdések rögzítése.",
    status: "Folyamatban",
    recurrence: "none",
    externalProvider: "none",
    externalEventId: "",
    syncStatus: "none",
    lastSyncedAt: null,
  },
  {
    id: "event-3",
    title: "Kooperáció",
    start: "2026-05-21T14:00:00",
    end: "2026-05-21T15:00:00",
    className: "dimpro-event-sky",
    meetingType: "Microsoft Teams-értekezlet",
    person: "Milán Urbánkó",
    location: "Online",
    description: "Tervezői kooperáció.",
    status: "Tervezett",
    recurrence: "none",
    externalProvider: "none",
    externalEventId: "",
    syncStatus: "none",
    lastSyncedAt: null,
  },
  {
    id: "event-4",
    title: "Heti zárás",
    start: "2026-05-22T16:00:00",
    end: "2026-05-22T17:00:00",
    className: "dimpro-event-indigo",
    meetingType: "Belső státusz",
    person: "DIMPROVER csapat",
    location: "Iroda",
    description: "Heti lezárás és következő hét előkészítése.",
    status: "Tervezett",
    recurrence: "none",
    externalProvider: "none",
    externalEventId: "",
    syncStatus: "none",
    lastSyncedAt: null,
  },
];
