drop function if exists public.commerce_inventory_apply_movement(uuid,uuid,uuid,text,text,numeric,numeric,numeric,text,text,uuid,timestamptz);
drop function if exists public.commerce_product_create_atomic(uuid,text,text,text,text,uuid,uuid,uuid,text,jsonb,jsonb);
-- DEV rollback for DIMPRO Commerce Core M0/M1 staged migration.
drop table if exists public.commerce_outbox_events cascade;
drop table if exists public.commerce_audit_events cascade;
drop table if exists public.commerce_stock_movements cascade;
drop table if exists public.commerce_inventory_balances cascade;
drop table if exists public.commerce_external_inventory_snapshots cascade;
drop table if exists public.commerce_inventory_sources cascade;
drop table if exists public.commerce_media_links cascade;
drop table if exists public.commerce_media_assets cascade;
drop table if exists public.commerce_prices cascade;
drop table if exists public.commerce_product_identifiers cascade;
drop table if exists public.commerce_product_variants cascade;
drop table if exists public.commerce_products cascade;
drop table if exists public.commerce_manufacturers cascade;
drop table if exists public.commerce_brands cascade;
drop table if exists public.commerce_categories cascade;
drop table if exists public.commerce_warehouses cascade;
drop table if exists public.commerce_storefronts cascade;
drop table if exists public.commerce_schema_meta cascade;
